<?php

$wgTranslateLanguageFallbacks['abs'] = array( 'id' );
$wgTranslateLanguageFallbacks['acf'] = 'fr';
$wgTranslateLanguageFallbacks['aeb'] = 'ar';
$wgTranslateLanguageFallbacks['af'] = 'nl';
$wgTranslateLanguageFallbacks['ady-cyrl'] = 'ru';
$wgTranslateLanguageFallbacks['aro'] = 'es';
$wgTranslateLanguageFallbacks['arq'] = 'ar';
$wgTranslateLanguageFallbacks['ary'] = 'ar';
$wgTranslateLanguageFallbacks['as'] = 'bn';
$wgTranslateLanguageFallbacks['ba'] = array( 'tt-cyrl', 'ru' );
$wgTranslateLanguageFallbacks['ban'] = array( 'id', 'jv' );
$wgTranslateLanguageFallbacks['bbc-latn'] = array( 'id', 'ms' ); # Robin 2011-20-16
$wgTranslateLanguageFallbacks['be-tarask'] = array( 'pl', 'ru', 'uk', 'be' );
$wgTranslateLanguageFallbacks['bew'] = 'id';
$wgTranslateLanguageFallbacks['bfq'] = array( 'kn', 'ta' );
$wgTranslateLanguageFallbacks['bjn'] = 'id';
$wgTranslateLanguageFallbacks['br'] = array( 'roa-rup', 'pms', 'fr', 'it' );
$wgTranslateLanguageFallbacks['cps'] = array( 'tl' );
$wgTranslateLanguageFallbacks['cs'] = array( 'sk', 'de', 'fr', 'ru', 'pl' );
$wgTranslateLanguageFallbacks['da'] = array( 'nn', 'nb', 'sv' ); # Siebrand 2008-03-23
$wgTranslateLanguageFallbacks['egl'] = array( 'it', 'rgn' );
$wgTranslateLanguageFallbacks['es-419'] = 'es';
$wgTranslateLanguageFallbacks['es-formal'] = 'es';
$wgTranslateLanguageFallbacks['et'] = 'fi';
$wgTranslateLanguageFallbacks['fi'] = array( 'de', 'sv', 'et', 'vro' );
$wgTranslateLanguageFallbacks['fit'] = array( 'fi', 'sv' ); # Robin 2011-09-27
$wgTranslateLanguageFallbacks['fy'] = 'nl';
$wgTranslateLanguageFallbacks['gcf'] = 'fr';
$wgTranslateLanguageFallbacks['gom'] = 'gom-deva';
$wgTranslateLanguageFallbacks['gom-deva'] = 'hi';
$wgTranslateLanguageFallbacks['guc'] = 'es';
$wgTranslateLanguageFallbacks['hi'] = 'mr'; # Siebrand 2008-03-25
$wgTranslateLanguageFallbacks['hif-deva'] = 'hi'; # Siebrand 2008-02-12
$wgTranslateLanguageFallbacks['hsn'] = 'zh-hans';
$wgTranslateLanguageFallbacks['hu-formal'] = 'hu';
$wgTranslateLanguageFallbacks['hy'] = 'ru';
$wgTranslateLanguageFallbacks['ia'] = array( 'fr', 'it', 'es', 'pt' );
$wgTranslateLanguageFallbacks['ka'] = 'de';
$wgTranslateLanguageFallbacks['kab'] = 'fr';
$wgTranslateLanguageFallbacks['kbd-cyrl'] = array( 'kbd-latn', 'ru' );
$wgTranslateLanguageFallbacks['kbd-latn'] = array( 'kbd-cyrl', 'tr' );
$wgTranslateLanguageFallbacks['kea'] = 'pt';
$wgTranslateLanguageFallbacks['kgp'] = array( 'pt', 'pt-br' );
$wgTranslateLanguageFallbacks['ki'] = 'sw';
$wgTranslateLanguageFallbacks['krl'] = 'fi';
$wgTranslateLanguageFallbacks['ks-arab'] = 'ur'; # Robin
$wgTranslateLanguageFallbacks['ks-deva'] = 'hi'; # Robin
$wgTranslateLanguageFallbacks['ksf'] = array( 'fr' ); # Robin 2011-10-21
$wgTranslateLanguageFallbacks['kv'] = 'ru';
$wgTranslateLanguageFallbacks['kw'] = array( 'br', 'cy' );
$wgTranslateLanguageFallbacks['lb'] = array( 'fr' );
$wgTranslateLanguageFallbacks['lez'] = array( 'ru', 'az' ); # Robin 2011-09-27
$wgTranslateLanguageFallbacks['lld'] = array( 'it', 'rm', 'fur' ); # Robin 2011-12-04
$wgTranslateLanguageFallbacks['lmo'] = array( 'pms', 'eml', 'lij', 'vec' );
$wgTranslateLanguageFallbacks['mai'] = 'hi';
$wgTranslateLanguageFallbacks['mdf'] = array( 'myv' );
$wgTranslateLanguageFallbacks['mfe'] = array( 'fr' ); # Robin 2011-10-18
$wgTranslateLanguageFallbacks['mhr'] = array( 'mrj' );
$wgTranslateLanguageFallbacks['miq'] = array( 'es' );
$wgTranslateLanguageFallbacks['mnc'] = array( 'zh-hans' );
$wgTranslateLanguageFallbacks['mrj'] = array( 'mhr' );
$wgTranslateLanguageFallbacks['mt'] = 'it'; # http://translatewiki.net/w/i.php?title=Support&curid=71166&diff=485516&oldid=485114
$wgTranslateLanguageFallbacks['mui'] = array( 'id' );
$wgTranslateLanguageFallbacks['mwv'] = array( 'id' );
$wgTranslateLanguageFallbacks['my'] = array( 'ru' );
$wgTranslateLanguageFallbacks['myv'] = array( 'mdf' );
$wgTranslateLanguageFallbacks['nds'] = array( 'da', 'nl', 'nds-nl', 'pdt' );
$wgTranslateLanguageFallbacks['nds-nl'] = array( 'nds', 'pdt' );
$wgTranslateLanguageFallbacks['njo'] = array( 'as', 'hi' );
$wgTranslateLanguageFallbacks['nl-be'] = array( 'nl' );
$wgTranslateLanguageFallbacks['nl-informal'] = array( 'nl' );
$wgTranslateLanguageFallbacks['nn'] = array( 'nb', 'sv', 'da' ); # Siebrand 2008-02-18
$wgTranslateLanguageFallbacks['nb'] = array( 'nn', 'da', 'sv' ); # Siebrand 2008-02-18
$wgTranslateLanguageFallbacks['pbb'] = array( 'es' );
$wgTranslateLanguageFallbacks['pdt'] = array( 'de' );
$wgTranslateLanguageFallbacks['ppl'] = array( 'es' );
$wgTranslateLanguageFallbacks['pt'] = array( 'pt-br', 'es', 'gl' ); # [[Thread:Support/wgTranslateLanguageFallbacks for Portuguese]]
$wgTranslateLanguageFallbacks['pt-br'] = array( 'es', 'gl' );
$wgTranslateLanguageFallbacks['prg'] = array( 'lv', 'lt' );
$wgTranslateLanguageFallbacks['qu'] = array( 'es', 'qug' );
$wgTranslateLanguageFallbacks['qug'] = array( 'es', 'qu' );
$wgTranslateLanguageFallbacks['rgn'] = array( 'it', 'egl' );
$wgTranslateLanguageFallbacks['rif'] = array( 'ar', 'fr' ); # Robin 2011-09-30
$wgTranslateLanguageFallbacks['rki'] = array( 'my' );
$wgTranslateLanguageFallbacks['rut'] = array( 'az', 'ru', 'lez' ); # Robin 2012-07-24
$wgTranslateLanguageFallbacks['ryu'] = array( 'ja' );
$wgTranslateLanguageFallbacks['saz'] = array( 'gu' );
$wgTranslateLanguageFallbacks['sdc'] = array( 'it' );
$wgTranslateLanguageFallbacks['se'] = array( 'fi', 'sv', 'nb', 'sma' );
$wgTranslateLanguageFallbacks['shi'] = array( 'ar', 'fr' ); # Robin 2011-09-27
$wgTranslateLanguageFallbacks['sli'] = array( 'pl', 'szl' );
$wgTranslateLanguageFallbacks['sly'] = array( 'id' );
$wgTranslateLanguageFallbacks['sma'] = array( 'sv', 'nb', 'se' );
$wgTranslateLanguageFallbacks['sv'] = array( 'da', 'nb', 'nn' ); # Siebrand 2008-03-23
$wgTranslateLanguageFallbacks['swb'] = 'sw';
$wgTranslateLanguageFallbacks['tet'] = 'pt';
$wgTranslateLanguageFallbacks['tkr'] = 'ru';
$wgTranslateLanguageFallbacks['tly'] = 'ru';
$wgTranslateLanguageFallbacks['tru'] = 'arc'; # Robin 2012-02-18
$wgTranslateLanguageFallbacks['tsd'] = 'el';
$wgTranslateLanguageFallbacks['ug-arab'] = array( 'ug-latn', 'zh-hans', 'zh-hant' ); # Robin 2011-11-14
$wgTranslateLanguageFallbacks['ug-latn'] = array( 'ug-arab', 'ru' ); # Robin 2011-11-14
$wgTranslateLanguageFallbacks['vep'] = array( 'fi', 'ru' );
$wgTranslateLanguageFallbacks['vro'] = array( 'fi', 'ru', 'de', 'hu' );
$wgTranslateLanguageFallbacks['wo'] = 'it';
$wgTranslateLanguageFallbacks['yrk'] = 'ru'; # Lcawte 2011-02-07
$wgTranslateLanguageFallbacks['yrl'] = array( 'es', 'pt-br' );
$wgTranslateLanguageFallbacks['yua'] = 'es';
