<?php

$wgTranslateLanguageFallbacks['abs'] = [ 'id' ];
$wgTranslateLanguageFallbacks['acf'] = 'fr';
$wgTranslateLanguageFallbacks['af'] = 'nl';
$wgTranslateLanguageFallbacks['ady-cyrl'] = 'ru';
$wgTranslateLanguageFallbacks['ais'] = [ 'zh-hant' ]; # Amir 2017-05-03
$wgTranslateLanguageFallbacks['alt'] = [ 'ru' ]; # Amir 2020-06-06
$wgTranslateLanguageFallbacks['ami'] = [ 'zh-hant' ]; # Amir 2017-05-03
$wgTranslateLanguageFallbacks['aro'] = 'es';
$wgTranslateLanguageFallbacks['ary'] = 'ar';
$wgTranslateLanguageFallbacks['as'] = 'bn';
$wgTranslateLanguageFallbacks['atj'] = 'fr';
$wgTranslateLanguageFallbacks['atv'] = [ 'ru' ]; # Amir 2020-06-06
$wgTranslateLanguageFallbacks['awa'] = [ 'hi' ];
$wgTranslateLanguageFallbacks['ba'] = [ 'tt-cyrl', 'ru' ];
$wgTranslateLanguageFallbacks['ban'] = [ 'id', 'jv' ];
$wgTranslateLanguageFallbacks['bbc-latn'] = [ 'id', 'ms' ]; # Robin 2011-20-16
$wgTranslateLanguageFallbacks['bci'] = 'fr';
$wgTranslateLanguageFallbacks['be-tarask'] = [ 'pl', 'ru', 'uk', 'be' ];
$wgTranslateLanguageFallbacks['bew'] = 'id';
$wgTranslateLanguageFallbacks['bft'] = 'ur';
$wgTranslateLanguageFallbacks['bfq'] = [ 'kn', 'ta' ];
$wgTranslateLanguageFallbacks['bjn'] = 'id';
$wgTranslateLanguageFallbacks['br'] = [ 'roa-rup', 'pms', 'fr', 'it' ];
$wgTranslateLanguageFallbacks['cak'] = [ 'es' ];
$wgTranslateLanguageFallbacks['cja-latn'] = [ 'km' ];
$wgTranslateLanguageFallbacks['cjm-latn'] = [ 'vi' ];
$wgTranslateLanguageFallbacks['cjy-hans'] = [ 'zh-hans' ];
$wgTranslateLanguageFallbacks['cjy-hant'] = [ 'zh-hant' ];
$wgTranslateLanguageFallbacks['cnh'] = [ 'my' ];
$wgTranslateLanguageFallbacks['cps'] = [ 'tl' ];
$wgTranslateLanguageFallbacks['cpx'] = [ 'cdo' ];
$wgTranslateLanguageFallbacks['cs'] = [ 'sk', 'de', 'fr', 'ru', 'pl' ];
$wgTranslateLanguageFallbacks['da'] = [ 'nn', 'nb', 'sv' ]; # Siebrand 2008-03-23
$wgTranslateLanguageFallbacks['dty'] = [ 'ne' ];
$wgTranslateLanguageFallbacks['egl'] = [ 'it', 'rgn' ];
$wgTranslateLanguageFallbacks['es-formal'] = 'es';
$wgTranslateLanguageFallbacks['es-mx'] = 'es';
$wgTranslateLanguageFallbacks['et'] = 'fi';
$wgTranslateLanguageFallbacks['fax'] = 'es';
$wgTranslateLanguageFallbacks['fi'] = [ 'de', 'sv', 'et', 'vro' ];
$wgTranslateLanguageFallbacks['fit'] = [ 'fi', 'sv' ]; # Robin 2011-09-27
$wgTranslateLanguageFallbacks['frc'] = 'fr'; # Ebe123 2014-08-25 ('lou' is not implemented)
$wgTranslateLanguageFallbacks['fy'] = 'nl';
$wgTranslateLanguageFallbacks['gcf'] = 'fr';
$wgTranslateLanguageFallbacks['gcr'] = 'fr';
$wgTranslateLanguageFallbacks['guc'] = 'es';
$wgTranslateLanguageFallbacks['gor'] = [ 'id' ];
$wgTranslateLanguageFallbacks['hak-hans'] = [ 'hak-hant', 'hak', 'zh-hans' ];
$wgTranslateLanguageFallbacks['hak-hant'] = [ 'hak-hans', 'hak', 'zh-hant' ];
$wgTranslateLanguageFallbacks['hi'] = 'mr'; # Siebrand 2008-03-25
$wgTranslateLanguageFallbacks['hif-deva'] = 'hi'; # Siebrand 2008-02-12
$wgTranslateLanguageFallbacks['hsn'] = 'zh-hans';
$wgTranslateLanguageFallbacks['hu-formal'] = 'hu';
$wgTranslateLanguageFallbacks['hy'] = 'ru';
$wgTranslateLanguageFallbacks['hyw'] = 'hy';
$wgTranslateLanguageFallbacks['ia'] = [ 'fr', 'it', 'es', 'pt' ];
$wgTranslateLanguageFallbacks['jdt-cyrl'] = 'ru';
$wgTranslateLanguageFallbacks['ka'] = 'de';
$wgTranslateLanguageFallbacks['kab'] = 'fr';
$wgTranslateLanguageFallbacks['kac'] = [ 'my' ];
$wgTranslateLanguageFallbacks['kbd-cyrl'] = [ 'kbd-latn', 'ru' ];
$wgTranslateLanguageFallbacks['kbd-latn'] = [ 'kbd-cyrl', 'tr' ];
$wgTranslateLanguageFallbacks['kbp'] = 'fr';
$wgTranslateLanguageFallbacks['kea'] = 'pt';
$wgTranslateLanguageFallbacks['kgp'] = [ 'pt', 'pt-br' ];
$wgTranslateLanguageFallbacks['ki'] = 'sw';
$wgTranslateLanguageFallbacks['kjh'] = 'ru';
$wgTranslateLanguageFallbacks['kjp'] = 'my';
$wgTranslateLanguageFallbacks['knn'] = 'hi';
$wgTranslateLanguageFallbacks['krl'] = 'fi';
$wgTranslateLanguageFallbacks['ks-arab'] = 'ur'; # Robin
$wgTranslateLanguageFallbacks['ks-deva'] = 'hi'; # Robin
$wgTranslateLanguageFallbacks['ksf'] = [ 'fr' ]; # Robin 2011-10-21
$wgTranslateLanguageFallbacks['kum'] = 'ru';
$wgTranslateLanguageFallbacks['kv'] = 'ru';
$wgTranslateLanguageFallbacks['kw'] = [ 'br', 'cy' ];
$wgTranslateLanguageFallbacks['lag'] = [ 'sw' ]; # Amir 2017-05-03
$wgTranslateLanguageFallbacks['lb'] = [ 'fr' ];
$wgTranslateLanguageFallbacks['lez'] = [ 'ru', 'az' ]; # Robin 2011-09-27
$wgTranslateLanguageFallbacks['lki'] = [ 'fa', 'lrc', 'sdh' ];
$wgTranslateLanguageFallbacks['lld'] = [ 'it', 'rm', 'fur' ]; # Robin 2011-12-04
$wgTranslateLanguageFallbacks['lmo'] = [ 'pms', 'eml', 'lij', 'vec' ];
$wgTranslateLanguageFallbacks['luz'] = [ 'fa' ];
$wgTranslateLanguageFallbacks['mad'] = 'id';
$wgTranslateLanguageFallbacks['mai'] = 'hi';
$wgTranslateLanguageFallbacks['mdf'] = [ 'myv' ];
$wgTranslateLanguageFallbacks['mfe'] = [ 'fr' ]; # Robin 2011-10-18
$wgTranslateLanguageFallbacks['mhr'] = [ 'mrj' ];
$wgTranslateLanguageFallbacks['miq'] = [ 'es' ];
$wgTranslateLanguageFallbacks['mnc'] = [ 'zh-hans' ];
$wgTranslateLanguageFallbacks['moe'] = [ 'fr' ];
$wgTranslateLanguageFallbacks['mrj'] = [ 'mhr' ];
$wgTranslateLanguageFallbacks['mt'] = 'it'; # http://translatewiki.net/w/i.php?title=Support&curid=71166&diff=485516&oldid=485114
$wgTranslateLanguageFallbacks['mui'] = [ 'id' ];
$wgTranslateLanguageFallbacks['mwv'] = [ 'id' ];
$wgTranslateLanguageFallbacks['my'] = [ 'ru' ];
$wgTranslateLanguageFallbacks['myv'] = [ 'mdf' ];
$wgTranslateLanguageFallbacks['nds'] = [ 'da', 'nl', 'nds-nl', 'pdt' ];
$wgTranslateLanguageFallbacks['nds-nl'] = [ 'nds', 'pdt' ];
$wgTranslateLanguageFallbacks['njo'] = [ 'as', 'hi' ];
$wgTranslateLanguageFallbacks['nod'] = 'th'; # Siebrand 2017-05-20
$wgTranslateLanguageFallbacks['nog'] = 'ru';
$wgTranslateLanguageFallbacks['nl-informal'] = [ 'nl' ];
$wgTranslateLanguageFallbacks['nn'] = [ 'nb', 'sv', 'da' ]; # Siebrand 2008-02-18
$wgTranslateLanguageFallbacks['nb'] = [ 'nn', 'da', 'sv' ]; # Siebrand 2008-02-18
$wgTranslateLanguageFallbacks['olo'] = [ 'ru' ]; # Mjbmr 2015-08-06
$wgTranslateLanguageFallbacks['ovd'] = [ 'se' ]; # Siebrand 2017-05-20
$wgTranslateLanguageFallbacks['pbb'] = [ 'es' ];
$wgTranslateLanguageFallbacks['pdt'] = [ 'de' ];
$wgTranslateLanguageFallbacks['ppl'] = [ 'es' ];
$wgTranslateLanguageFallbacks['pt'] = [ 'pt-br', 'es', 'gl' ]; # [[Thread:Support/wgTranslateLanguageFallbacks for Portuguese]]
$wgTranslateLanguageFallbacks['pt-br'] = [ 'es', 'gl' ];
$wgTranslateLanguageFallbacks['prg'] = [ 'lv', 'lt' ];
$wgTranslateLanguageFallbacks['prs'] = [ 'fa', 'ps' ];
$wgTranslateLanguageFallbacks['qu'] = [ 'es', 'qug' ];
$wgTranslateLanguageFallbacks['qug'] = [ 'es', 'qu' ];
$wgTranslateLanguageFallbacks['qwh'] = [ 'qu', 'es' ];
$wgTranslateLanguageFallbacks['rcf'] = [ 'fr' ];
$wgTranslateLanguageFallbacks['rgn'] = [ 'it', 'egl' ];
$wgTranslateLanguageFallbacks['rif'] = [ 'ar', 'fr' ]; # Robin 2011-09-30
$wgTranslateLanguageFallbacks['rki'] = [ 'my' ];
$wgTranslateLanguageFallbacks['rmf'] = [ 'fi' ];
$wgTranslateLanguageFallbacks['rut'] = [ 'az', 'ru', 'lez' ]; # Robin 2012-07-24
$wgTranslateLanguageFallbacks['ryu'] = [ 'ja' ];
$wgTranslateLanguageFallbacks['saz'] = [ 'gu' ];
$wgTranslateLanguageFallbacks['sdc'] = [ 'it' ];
$wgTranslateLanguageFallbacks['sdh'] = [ 'cbk' ];
$wgTranslateLanguageFallbacks['se'] = [ 'fi', 'sv', 'nb', 'sma' ];
$wgTranslateLanguageFallbacks['shi'] = [ 'ar', 'fr' ]; # Robin 2011-09-27
$wgTranslateLanguageFallbacks['shy-latn'] = [ 'fr' ];
$wgTranslateLanguageFallbacks['sli'] = [ 'pl', 'szl' ];
$wgTranslateLanguageFallbacks['sly'] = [ 'id' ];
$wgTranslateLanguageFallbacks['sma'] = [ 'sv', 'nb', 'se' ];
$wgTranslateLanguageFallbacks['smj'] = [ 'nb' ];
$wgTranslateLanguageFallbacks['smn'] = [ 'fi', 'sma' ];
$wgTranslateLanguageFallbacks['sv'] = [ 'da', 'nb', 'nn' ]; # Siebrand 2008-03-23
$wgTranslateLanguageFallbacks['swb'] = 'sw';
$wgTranslateLanguageFallbacks['tet'] = 'pt';
$wgTranslateLanguageFallbacks['tji'] = 'zh-hans';
$wgTranslateLanguageFallbacks['tkr'] = 'ru';
$wgTranslateLanguageFallbacks['tly'] = 'ru';
$wgTranslateLanguageFallbacks['tru'] = 'arc'; # Robin 2012-02-18
$wgTranslateLanguageFallbacks['trv'] = [ 'zh-hant' ]; # Amir 2017-05-03
$wgTranslateLanguageFallbacks['tsd'] = 'el';
$wgTranslateLanguageFallbacks['ug-arab'] = [ 'ug-latn', 'zh-hans', 'zh-hant' ]; # Robin 2011-11-14
$wgTranslateLanguageFallbacks['ug-latn'] = [ 'ug-arab', 'ru' ]; # Robin 2011-11-14
$wgTranslateLanguageFallbacks['vep'] = [ 'fi', 'ru' ];
$wgTranslateLanguageFallbacks['vro'] = [ 'fi', 'ru', 'de', 'hu' ];
$wgTranslateLanguageFallbacks['wo'] = 'it';
$wgTranslateLanguageFallbacks['xsy'] = [ 'zh-hant' ]; # Amir 2017-05-03
$wgTranslateLanguageFallbacks['yrk'] = 'ru'; # Lcawte 2011-02-07
$wgTranslateLanguageFallbacks['yrl'] = [ 'es', 'pt-br' ];
$wgTranslateLanguageFallbacks['yua'] = 'es';
