<?php
/** Local translatewiki fallback settings.
 *
 * Adding a value here makes the languages in it appear by default
 * as "assistant languages" to people who translate to the language listed
 * as the key and who have the default value in the assistant language
 * preferecnce. This value is added to the existing fallback language value
 * as defined in core MediaWiki.
 *
 */

$wgTranslateLanguageFallbacks['acf'] = 'fr';
$wgTranslateLanguageFallbacks['af'] = 'nl';
$wgTranslateLanguageFallbacks['ajg'] = [ 'fr', 'ee', 'fon', 'guw' ];
$wgTranslateLanguageFallbacks['ajp'] = 'ar';
$wgTranslateLanguageFallbacks['ak'] = 'tw';
$wgTranslateLanguageFallbacks['ale'] = [ 'ale-cyrl', 'ru', 'esu', 'ik', 'ike-cans', 'ike-latn', 'kl' ];
$wgTranslateLanguageFallbacks['ale-cyrl'] = [ 'ale', 'ru', 'esu', 'ik', 'ike-cans', 'ike-latn', 'kl' ];
$wgTranslateLanguageFallbacks['aro'] = 'es';
$wgTranslateLanguageFallbacks['as'] = 'bn';
$wgTranslateLanguageFallbacks['atv'] = [ 'ru' ]; # Amir 2020-06-06
$wgTranslateLanguageFallbacks['ba'] = [ 'tt-cyrl', 'ru' ];
$wgTranslateLanguageFallbacks['ban'] = [ 'id', 'jv' ];
$wgTranslateLanguageFallbacks['bas'] = [ 'fr' ];
$wgTranslateLanguageFallbacks['bbc-latn'] = [ 'id', 'ms' ]; # Robin 2011-20-16
$wgTranslateLanguageFallbacks['bew'] = 'id';
$wgTranslateLanguageFallbacks['bfq'] = [ 'kn', 'ta' ];
$wgTranslateLanguageFallbacks['bft'] = 'ur';
$wgTranslateLanguageFallbacks['bkm'] = 'fr';
$wgTranslateLanguageFallbacks['bm'] = 'nqo';
$wgTranslateLanguageFallbacks['bum'] = [ 'fr' ];
$wgTranslateLanguageFallbacks['bxr'] = [ 'mn', 'xal' ];
$wgTranslateLanguageFallbacks['bzj'] = [ 'jam', 'es' ];
$wgTranslateLanguageFallbacks['cak'] = [ 'es' ];
$wgTranslateLanguageFallbacks['cja-latn'] = [ 'km' ];
$wgTranslateLanguageFallbacks['cjm-latn'] = [ 'vi' ];
$wgTranslateLanguageFallbacks['cjy-hans'] = [ 'zh-hans' ];
$wgTranslateLanguageFallbacks['cjy-hant'] = [ 'zh-hant' ];
$wgTranslateLanguageFallbacks['cnh'] = [ 'my' ];
$wgTranslateLanguageFallbacks['cps'] = [ 'tl' ];
$wgTranslateLanguageFallbacks['cpx'] = [ 'cdo' ];
$wgTranslateLanguageFallbacks['cs'] = [ 'sk', 'de', 'fr', 'ru', 'pl' ];
$wgTranslateLanguageFallbacks['da'] = [ 'nn', 'nb', 'sv' ]; # Siebrand 2008-03-23
$wgTranslateLanguageFallbacks['dar'] = [ 'av', 'ce', 'ru', 'az' ];
$wgTranslateLanguageFallbacks['ee'] = [ 'fr', 'ajg', 'fon', 'guw' ];
$wgTranslateLanguageFallbacks['egl'] = [ 'it', 'rgn' ];
$wgTranslateLanguageFallbacks['es-mx'] = 'es';
$wgTranslateLanguageFallbacks['esu'] = [ 'ale', 'ale-cyrl', 'ik', 'ike-cans', 'ike-latn', 'kl' ];
$wgTranslateLanguageFallbacks['et'] = 'fi';
$wgTranslateLanguageFallbacks['fax'] = 'es';
$wgTranslateLanguageFallbacks['fi'] = [ 'de', 'sv', 'et', 'vro' ];
$wgTranslateLanguageFallbacks['fit'] = [ 'fi', 'sv' ]; # Robin 2011-09-27
$wgTranslateLanguageFallbacks['fon'] = [ 'ajg', 'ee', 'guw', 'yo' ];
$wgTranslateLanguageFallbacks['fy'] = 'nl';
$wgTranslateLanguageFallbacks['gaa'] = [ 'tw', 'bci' ];
$wgTranslateLanguageFallbacks['gcf'] = 'fr';
$wgTranslateLanguageFallbacks['guw'] = [ 'fr', 'fon', 'ajg', 'ee', 'yo' ];
$wgTranslateLanguageFallbacks['hak-hans'] = [ 'hak-hant', 'hak', 'zh-hans' ];
$wgTranslateLanguageFallbacks['hak-hant'] = [ 'hak-hans', 'hak', 'zh-hant' ];
$wgTranslateLanguageFallbacks['hi'] = 'mr'; # Siebrand 2008-03-25
$wgTranslateLanguageFallbacks['hif-deva'] = 'hi'; # Siebrand 2008-02-12
$wgTranslateLanguageFallbacks['hy'] = 'ru';
$wgTranslateLanguageFallbacks['ia'] = [ 'fr', 'it', 'es', 'pt' ];
$wgTranslateLanguageFallbacks['ik'] = [ 'ale', 'ale-cyrl', 'esu', 'ike-cans', 'ike-latn', 'kl' ];
$wgTranslateLanguageFallbacks['ike-cans'] = [ 'ale', 'ale-cyrl', 'esu', 'ik', 'ike-latn', 'kl' ];
$wgTranslateLanguageFallbacks['ike-latn'] = [ 'ale', 'ale-cyrl', 'esu', 'ik', 'ike-cans', 'kl' ];
$wgTranslateLanguageFallbacks['jdt-cyrl'] = 'ru';
$wgTranslateLanguageFallbacks['kac'] = [ 'my' ];
$wgTranslateLanguageFallbacks['kgp'] = [ 'pt', 'pt-br' ];
$wgTranslateLanguageFallbacks['ki'] = 'sw';
$wgTranslateLanguageFallbacks['kjh'] = 'ru';
$wgTranslateLanguageFallbacks['kl'] = [ 'ale', 'ale-cyrl', 'esu', 'ik', 'ike-cans', 'ike-latn' ];
$wgTranslateLanguageFallbacks['knn'] = 'hi';
$wgTranslateLanguageFallbacks['ks-arab'] = 'ur'; # Robin
$wgTranslateLanguageFallbacks['ks-deva'] = 'hi'; # Robin
$wgTranslateLanguageFallbacks['ksf'] = [ 'fr' ]; # Robin 2011-10-21
$wgTranslateLanguageFallbacks['lag'] = [ 'sw' ]; # Amir 2017-05-03
$wgTranslateLanguageFallbacks['lki'] = [ 'fa', 'lrc', 'sdh' ];
$wgTranslateLanguageFallbacks['mfe'] = [ 'fr' ]; # Robin 2011-10-18
$wgTranslateLanguageFallbacks['miq'] = [ 'es' ];
$wgTranslateLanguageFallbacks['mnc'] = [ 'zh-hans' ];
$wgTranslateLanguageFallbacks['moe'] = [ 'fr' ];
$wgTranslateLanguageFallbacks['mos'] = [ 'fr', 'dag', 'gur', 'kbp', 'nmz' ];
$wgTranslateLanguageFallbacks['mui'] = [ 'id' ];
$wgTranslateLanguageFallbacks['mvf'] = [ 'mn', 'zh-hans', 'ru' ];
$wgTranslateLanguageFallbacks['mwv'] = [ 'id' ];
$wgTranslateLanguageFallbacks['nb'] = [ 'nn', 'da', 'sv' ]; # Siebrand 2008-02-18
$wgTranslateLanguageFallbacks['nds-nl'] = [ 'nds', 'pdt' ];
$wgTranslateLanguageFallbacks['nds'] = [ 'da', 'nl', 'nds-nl', 'pdt' ];
$wgTranslateLanguageFallbacks['njo'] = [ 'as', 'hi' ];
$wgTranslateLanguageFallbacks['nmz'] = [ 'fr', 'kbp', 'ee' ]; # Only for translatewiki. Don't add these as fallback in core.
$wgTranslateLanguageFallbacks['nn'] = [ 'nb', 'sv', 'da' ]; # Siebrand 2008-02-18
$wgTranslateLanguageFallbacks['nod'] = [ 'th', 'nod-thai' ]; # Amir 2011-11-07
$wgTranslateLanguageFallbacks['nod-thai'] = [ 'th', 'nod' ]; # Siebrand 2017-05-20
$wgTranslateLanguageFallbacks['nog'] = 'ru';
$wgTranslateLanguageFallbacks['nqo'] = [ 'fr', 'bm' ];
$wgTranslateLanguageFallbacks['nus'] = [ 'ar', 'din' ];
$wgTranslateLanguageFallbacks['nyn'] = [ 'lg', 'sw', 'rw', 'rn', 'rag' ];
$wgTranslateLanguageFallbacks['olo'] = [ 'ru' ]; # Mjbmr 2015-08-06
$wgTranslateLanguageFallbacks['ovd'] = [ 'se' ]; # Siebrand 2017-05-20
$wgTranslateLanguageFallbacks['pap'] = [ 'pap-aw', 'nl', 'pt', 'es' ];
$wgTranslateLanguageFallbacks['pap-aw'] = [ 'pap', 'nl', 'pt', 'es' ];
$wgTranslateLanguageFallbacks['pbb'] = [ 'es' ];
$wgTranslateLanguageFallbacks['ppl'] = [ 'es' ];
$wgTranslateLanguageFallbacks['prg'] = [ 'lv', 'lt', 'sgs', 'ltg', 'pl', 'ru' ];
$wgTranslateLanguageFallbacks['prs'] = [ 'fa', 'ps' ];
$wgTranslateLanguageFallbacks['pt-br'] = [ 'es', 'gl' ];
$wgTranslateLanguageFallbacks['pt'] = [ 'pt-br', 'es', 'gl' ]; # [[Thread:Support/wgTranslateLanguageFallbacks for Portuguese]]
$wgTranslateLanguageFallbacks['pwn'] = [ 'ami', 'tay', 'xsy', 'szy', 'trv' ];
$wgTranslateLanguageFallbacks['qwh'] = [ 'qu', 'es' ];
$wgTranslateLanguageFallbacks['rag'] = [ 'sw', 'nyn', 'rw', 'rn', 'lg' ];
$wgTranslateLanguageFallbacks['rcf'] = [ 'fr' ];
$wgTranslateLanguageFallbacks['rif'] = [ 'ar', 'fr' ]; # Robin 2011-09-30
$wgTranslateLanguageFallbacks['rki'] = [ 'my' ];
$wgTranslateLanguageFallbacks['rmc'] = [ 'sk', 'cs', 'hu' ];
$wgTranslateLanguageFallbacks['rmf'] = [ 'fi' ];
$wgTranslateLanguageFallbacks['rn'] = [ 'fr', 'rw', 'sw' ];
$wgTranslateLanguageFallbacks['rsk'] = [ 'sr-cyrl', 'uk', 'ru' ];
$wgTranslateLanguageFallbacks['rut'] = [ 'az', 'ru', 'lez' ]; # Robin 2012-07-24
$wgTranslateLanguageFallbacks['rw'] = [ 'fr', 'rn', 'sw' ];
$wgTranslateLanguageFallbacks['ryu'] = [ 'ja' ];
$wgTranslateLanguageFallbacks['so'] = [ 'ar', 'it' ];
$wgTranslateLanguageFallbacks['saz'] = [ 'gu' ];
$wgTranslateLanguageFallbacks['se'] = [ 'fi', 'sv', 'nb', 'sma' ];
$wgTranslateLanguageFallbacks['shi'] = [ 'ar', 'fr' ]; # Robin 2011-09-27
$wgTranslateLanguageFallbacks['shy'] = [ 'fr', 'kab', 'arq', 'ar' ];
$wgTranslateLanguageFallbacks['sje'] = [ 'smj', 'se', 'sma', 'sv', 'nb', 'nn' ];
$wgTranslateLanguageFallbacks['sli'] = [ 'pl', 'szl' ];
$wgTranslateLanguageFallbacks['sly'] = [ 'id' ];
$wgTranslateLanguageFallbacks['sma'] = [ 'sv', 'nb', 'se' ];
$wgTranslateLanguageFallbacks['smj'] = [ 'nb' ];
$wgTranslateLanguageFallbacks['smn'] = [ 'fi', 'sma' ];
$wgTranslateLanguageFallbacks['swb'] = 'sw';
$wgTranslateLanguageFallbacks['tji'] = 'zh-hans';
$wgTranslateLanguageFallbacks['tkr'] = 'ru';
$wgTranslateLanguageFallbacks['tly'] = [ 'tly-cyrl', 'az', 'azb', 'fa', 'ru' ];
$wgTranslateLanguageFallbacks['tly-cyrl'] = [ 'tly', 'az', 'azb', 'fa', 'ru' ];
$wgTranslateLanguageFallbacks['tru'] = 'arc'; # Robin 2012-02-18
$wgTranslateLanguageFallbacks['tsd'] = 'el';
$wgTranslateLanguageFallbacks['tw'] = 'ak';
$wgTranslateLanguageFallbacks['ug-arab'] = [ 'ug-latn', 'zh-hans', 'zh-hant' ]; # Robin 2011-11-14
$wgTranslateLanguageFallbacks['ug-latn'] = [ 'ug-arab', 'ru' ]; # Robin 2011-11-14
$wgTranslateLanguageFallbacks['vmw'] = [ 'ts', 'sw', 'ss', 'ny', 'zu' ]; # Amir 2021-08-05
$wgTranslateLanguageFallbacks['xal'] = [ 'mn', 'bxr' ];
$wgTranslateLanguageFallbacks['xsy'] = [ 'zh-hant' ]; # Amir 2017-05-03
$wgTranslateLanguageFallbacks['yrk'] = 'ru'; # Lcawte 2011-02-07
$wgTranslateLanguageFallbacks['yrl'] = [ 'es', 'pt-br', 'gn' ];
$wgTranslateLanguageFallbacks['yua'] = 'es';
