<?php

$wgExtraLanguageNames['acf'] = 'kwéyòl'; # Saint Lucian Creole French / Siebrand 2012-08-05
$wgExtraLanguageNames['ahr'] = 'अहिराणी'; # Ahirani / Amir 2012-02-25
$wgExtraLanguageNames['akz'] = 'Albaamo innaaɬiilka'; # Alabama / Siebrand 2008-09-15
$wgExtraLanguageNames['als'] = 'Tosk'; # Correct incorrect name from MediaWiki core / Nike 2016-05-04
$wgExtraLanguageNames['ann'] = 'Obolo'; # Obolo / Amir 2020-07-01
$wgExtraLanguageNames['aro'] = 'Araona'; # Araona / Siebrand 2010-08-25
$wgExtraLanguageNames['atv'] = 'тÿндÿк алтай'; # Northern Altay / Amir 2020-06-07
$wgExtraLanguageNames['bci'] = 'Wawle'; # Baoulé / Amir 2020-06-03
$wgExtraLanguageNames['bdr'] = 'Bajau Sama'; # Bajau Sama / Amir 2020-12-25
$wgExtraLanguageNames['bew'] = 'Bahasa Betawi'; # Betawi / Siebrand 2008-07-13
$wgExtraLanguageNames['bft'] = 'بلتی'; # Balti / Nikerabbit 2016-06-22
$wgExtraLanguageNames['bfq'] = 'படகா'; # UBadaga / Siebrand 2009-11-19
$wgExtraLanguageNames['blc'] = 'ItNuxalkmc'; # Nuxalk / Amir 2020-06-22
$wgExtraLanguageNames['brx'] = 'बर\''; # Boro / Siebrand 2017-05-20
$wgExtraLanguageNames['cak'] = 'Kaqchikel'; # Kaqchikel / Nikerabbit 2018-06-15
$wgExtraLanguageNames['ccp'] = '𑄌𑄋𑄴𑄟𑄳𑄦'; # Chakma / Amir 2019-09-04
$wgExtraLanguageNames['ciw'] = 'Ojibwemowin'; # Chippewa / Siebrand 2014-03-21
$wgExtraLanguageNames['cja-latn'] = 'Cham Gah Pai'; # Western Cham (Latin script) / 2015-06-XX
$wgExtraLanguageNames['cjm-latn'] = 'Cham Gah Pur'; # Eastern Cham (Latin script) / Siebrand 2015-05-25
$wgExtraLanguageNames['cjy'] = '晉語'; # Jin Chinese (Jinnish) / 2015-06-XX
$wgExtraLanguageNames['cjy-hans'] = '晋语（简化字）'; # Jin Chinese (hans script) / 2015-06-XX
$wgExtraLanguageNames['cjy-hant'] = '晉語（正字）'; # Jin Chinese (hant script) / 2015-06-XX
$wgExtraLanguageNames['cnr-cyrl'] = 'црногорски'; # Montenegrin Cyrillic / Amir 2018-09-04
$wgExtraLanguageNames['cnr-latn'] = 'crnogorski'; # Montenegrin Latin / Amir 2018-09-04
$wgExtraLanguageNames['cnh'] = 'Lai holh'; # Haka Chin / Siebrand 2014-08-06
$wgExtraLanguageNames['cop'] = 'ϯⲙⲉⲧⲣⲉⲙⲛ̀ⲭⲏⲙⲓ'; # Coptic / Amir 2017-07-27
$wgExtraLanguageNames['cpx'] = 'Pó-sing-gṳ̂'; # Pu-Xian Min (莆仙語) / 2016-06-22
$wgExtraLanguageNames['dag'] = 'dagbanli'; # Dagbani / Amir 2017-06-01
$wgExtraLanguageNames['elm'] = 'Eleme'; # Eleme / Amir 2020-07-02
$wgExtraLanguageNames['es-formal'] = 'español (formal)'; # Spanish (formal address) / Siebrand 2010-11-22
$wgExtraLanguageNames['esu'] = 'Yup\'ik'; # Central Alaskan Yupik / Siebrand 2011-02-14
$wgExtraLanguageNames['fax'] = 'Fala'; # Fala / Nikerabbit 2016-06-22
$wgExtraLanguageNames['fon'] = 'Fon'; # Fon / Amir 2018-05-18
$wgExtraLanguageNames['gaa'] = 'Ga'; # Ga / Amir 2018-08-15
$wgExtraLanguageNames['gah'] = 'Alekano'; # Alekano / Siebrand 2010-10-08
$wgExtraLanguageNames['gbm'] = 'गढ़वळि'; # Garhwali / Amir 2020-03-14
$wgExtraLanguageNames['gbz'] = 'Dari-e Mazdeyasnā'; # Zoroastrian Dari / Siebrand 2011-01-20
$wgExtraLanguageNames['gcf'] = 'Guadeloupean Creole French'; # Guadeloupean Creole French / Siebrand 2009-09-21
$wgExtraLanguageNames['gld'] = 'На̄ни'; # Nanai / Amir 2021-01-15
$wgExtraLanguageNames['guc'] = 'Wayúu'; # Wayuu / Siebrand 2009-12-12
$wgExtraLanguageNames['gum'] = 'Namtrik'; # Guambiano / Amir 2017-03-27
$wgExtraLanguageNames['gur'] = 'Gurenɛ'; # Farefare / Siebrand 2011-01-27
$wgExtraLanguageNames['guw'] = 'Gungbe'; # Gungbe / Amir 2021-01-15
$wgExtraLanguageNames['hak-hans'] = '客家语（简体）'; # Hakka Chinese (Simplified Han script) / Siebrand 2017-05-20
$wgExtraLanguageNames['hak-hant'] = '客家語（繁體）'; # Hakka Chinese (Traditional Han script) / Siebrand 2017-05-20
$wgExtraLanguageNames['hif-deva'] = 'फ़ीजी हिन्दी'; # Fiji Hindi (Devangari script) / Siebrand 2010-08-26
$wgExtraLanguageNames['hne'] = 'छत्तीसगढ़ी'; # Amir 2011-12-01
$wgExtraLanguageNames['hoc'] = '𑢹𑣉𑣉'; # Ho language. Amir 2017-07-09
$wgExtraLanguageNames['hsn'] = '湘语'; # Xiang Chinese / Siebrand 2011-04-06
$wgExtraLanguageNames['hu-formal'] = 'Magyar (magázó)'; # Siebrand 2009-01-01
$wgExtraLanguageNames['izh'] = 'ižoran keel'; # Ingrian / Robin 2012-11-17 / Language classified as not written in Ethnologue. Should be removed.
$wgExtraLanguageNames['jdt-cyrl'] = 'жугьури'; # Judeo-Tat / Siebrand 2014-06-17
$wgExtraLanguageNames['kac'] = 'Jinghpaw'; # Jingpho / Siebrand 2014-04-08
$wgExtraLanguageNames['kbd-latn'] = 'Qabardjajəbza'; # Kabardian (Latin script) / Siebrand 2010-02-21
$wgExtraLanguageNames['kea'] = 'Kabuverdianu'; # Kabuverdianu / Siebrand 2009-01-07
$wgExtraLanguageNames['kgp'] = 'Kaingáng'; # Siebrand 2008-12-05
$wgExtraLanguageNames['kip'] = 'शेषी पाङ'; # Amir 2017-08-13
$wgExtraLanguageNames['kjh'] = 'хакас'; # Khakas / Amire80 2014-06-17
$wgExtraLanguageNames['kjp'] = 'ဖၠုံလိက်'; # Eastern Pwo Karen / Amire80 2018-09-02
$wgExtraLanguageNames['knn'] = 'महाराष्ट्रीय कोंकणी'; # Maharashtrian Konkani / 2015-XX-XX
$wgExtraLanguageNames['ksf'] = 'Bafia'; # Robin 2011-10-21
$wgExtraLanguageNames['ksw'] = 'စှီၤ ကညီကျိာ်'; # Sgaw Karen / Amir 2019-01-19
$wgExtraLanguageNames['lag'] = 'Kilaangi'; # Rangi / Amir 2017-05-03
$wgExtraLanguageNames['lad-hebr'] = 'לאדינו'; # Ladino in Hebrew script / Amir 2020-04-17
$wgExtraLanguageNames['lou'] = 'kréyol la lwizyàn'; # Louisiana Creole / Amir 2020-03-25
$wgExtraLanguageNames['lkt'] = 'Lakȟótiyapi'; # Lakota / 2014-04-08
$wgExtraLanguageNames['mad'] = 'Madhurâ'; # Madurese / Amir 2020-05-20
$wgExtraLanguageNames['mfe'] = 'Morisyen'; # Robin 2011-10-18
$wgExtraLanguageNames['mic'] = 'Mi\'kmaq'; # Micmac / Nikerabbit 2012-02-27
$wgExtraLanguageNames['miq'] = 'Mískitu'; # Miskito / Siebrand 2013-07-02
$wgExtraLanguageNames['mnc'] = 'ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ'; # Manchu / Siebrand 2010-08-11
$wgExtraLanguageNames['mnw'] = 'ဘာသာ မန်'; # Mon / Amir 2012-05-31
$wgExtraLanguageNames['moe'] = 'innu-aimun'; # Innu-aimun / Amir 2020-04-16
$wgExtraLanguageNames['mrh'] = 'Mara'; # Mara / Amir 2020-07-01
$wgExtraLanguageNames['mrv'] = 'Magareva'; # Mangareva / Amir 2019-08-28
$wgExtraLanguageNames['mui'] = 'Musi'; # Musi / Siebrand 2010-02-11
$wgExtraLanguageNames['mvf'] = 'ᠮᠣᠩᠭᠣᠯ'; # Southern Mongolian / Amir 2020-04-17
$wgExtraLanguageNames['mwv'] = 'Behase Mentawei'; # Mentawai / Siebrand 2008-05-07
$wgExtraLanguageNames['mww-latn'] = 'Hmoob Dawb'; # Hmong Daw / Siebrand 2013-12-02
$wgExtraLanguageNames['njo'] = 'Ao'; # Ao Naga
$wgExtraLanguageNames['nod'] = 'คำเมือง'; # Northern Thai / Siebrand 2017-05-20
$wgExtraLanguageNames['nog'] = 'Ногайша'; # Nogai / Nikerabbit 2018-08-03
$wgExtraLanguageNames['nys'] = 'Nyungar'; # Nyungar / Amir 2017-03-31
$wgExtraLanguageNames['oka'] = 'n̓səl̓xcin̓'; # Okanagan Salish / Amir 2018-04-04
$wgExtraLanguageNames['osi'] = 'Using'; # Osing / Amir 2019-08-31
$wgExtraLanguageNames['ovd'] = 'övdalsk'; # Övdalian / Siebrand 2017-05-20
$wgExtraLanguageNames['pbb'] = 'Nasa Yuwe'; # Páez / Siebrand 2013-08-08
$wgExtraLanguageNames['pis'] = 'Pijin'; # Pijin / Siebrand 2011-08-25
$wgExtraLanguageNames['pko'] = 'Pökoot'; # Pökoot
$wgExtraLanguageNames['pov'] = 'guinensi'; # Guinea-Bissau Creole / Amir 2019-05-17
$wgExtraLanguageNames['ppl'] = 'Nawat'; # Pipil / Siebrand 2011-08-30
$wgExtraLanguageNames['prs'] = 'دری'; # Dari
$wgExtraLanguageNames['pru'] = 'Prūsiskan'; # Prussian
$wgExtraLanguageNames['qwh'] = 'anqash qichwa'; # Amir 2018-03-04
$wgExtraLanguageNames['rap'] = 'arero rapa nui'; # Rapa Nui / Siebrand 2009-11-13
$wgExtraLanguageNames['rcf'] = 'Kreol Réyoné'; # Réunion Creole French / 2014-04-08
$wgExtraLanguageNames['rej'] = 'Jang'; # Rejang / Amir 2019-05-13
$wgExtraLanguageNames['rki'] = 'ရခိုင်'; # Rakhine / Siebrand 2010-10-14
$wgExtraLanguageNames['rmf'] = 'kaalengo tšimb'; # Romani language spoken in Finland / Nike 2014-03-05
$wgExtraLanguageNames['rtm'] = 'Faeag Rotuma'; # Rotuman
$wgExtraLanguageNames['ruq-grek'] = 'Megleno-Romanian (Greek script)'; # Megleno-Romanian (Greek script) / Siebrand 2009-09-23
$wgExtraLanguageNames['rut'] = 'мыхӀабишды'; # Rutul / Robin 2012-07-24
$wgExtraLanguageNames['ryu'] = 'ʔucināguci'; # Central Okinawan / Siebrand 2008-08-28
$wgExtraLanguageNames['saz'] = 'ꢱꣃꢬꢵꢯ꣄ꢡ꣄ꢬꢵ'; # Saurashtra / Siebrand 2011-03-17
$wgExtraLanguageNames['shn'] = 'လိၵ်ႈတႆး'; # Shan / Siebrand 2011-09-06
$wgExtraLanguageNames['shy-latn'] = 'Tacawit'; # Tacawit (Latin script) / Siebrand 2015-05-25
$wgExtraLanguageNames['sjd'] = 'кӣллт са̄мь кӣлл'; # Kildin Sámi / Amir 2020-03-31
$wgExtraLanguageNames['slr'] = 'Salırça'; # Salar / Siebrand 2008-08-18
$wgExtraLanguageNames['sly'] = 'Bahasa Selayar'; # A Selayar / Siebrand 2012-01-09
$wgExtraLanguageNames['smj'] = 'julevsámegiella'; # Lule Saami / Nikerabbit 2016-06-22
$wgExtraLanguageNames['sms'] = 'nuõrttsääʹmǩiõll'; # Skolt Sami / Niklas 2020-03-25
$wgExtraLanguageNames['sty'] = 'Себертатар'; # Siberian Tatar / Amir 2016-11-26
$wgExtraLanguageNames['swb'] = 'Shikomoro'; # Comorian
$wgExtraLanguageNames['sxu'] = 'Säggssch'; # Upper Saxon
$wgExtraLanguageNames['syl'] = 'ꠍꠤꠟꠐꠤ'; # Sylheti / Amir 2020-04-16
$wgExtraLanguageNames['tji'] = 'pi tsi kha'; # Northern Tujia / 2016-06-22
$wgExtraLanguageNames['tkr'] = 'ЦӀаӀхна миз'; # Tsakhur / Siebrand 2011-04-26
$wgExtraLanguageNames['trp'] = 'Kokborok (Tripuri)'; # Kokborok
$wgExtraLanguageNames['tsd'] = 'Τσακωνικά'; # Tsakonian / Siebrand 2009-08-20
$wgExtraLanguageNames['ttt'] = 'Tati'; # Tat / Siebrand 2008-04-04
$wgExtraLanguageNames['twd'] = 'Tweants'; # Twents
$wgExtraLanguageNames['vai'] = 'ꕙꔤ'; # Vai Amir 2019-04-23
$wgExtraLanguageNames['wls'] = 'Faka\'uvea'; # Fakauvea
$wgExtraLanguageNames['ydd'] = 'Eastern Yiddish'; # Eastern Yiddish / Siebrand 2009-09-23
$wgExtraLanguageNames['yrk'] = 'Ненэцяʼ вада'; # Tundra Nenets / Lcawte 2011-02-07
$wgExtraLanguageNames['yrl'] = 'ñe\'engatú'; # Nheengatu / Siebrand 2008-04-06
$wgExtraLanguageNames['yua'] = 'Maaya T\'aan'; # Yucatán Maya / Siebrand 2011-04-09
$wgExtraLanguageNames['qqq'] = 'Message documentation'; # No linguistic content. Used for documenting messages
