<?php

$wgExtraLanguageNames['abs'] = 'Bahasa Ambon'; # Ambonese Malay / Siebrand 2013-07-05
$wgExtraLanguageNames['acf'] = 'kwéyòl'; # Saint Lucian Creole French / Siebrand 2012-08-05
$wgExtraLanguageNames['ahr'] = 'अहिराणी'; # # Ahirani / Amir 2012-02-25
$wgExtraLanguageNames['akz'] = 'Albaamo innaaɬiilka'; # Alabama / Siebrand 2008-09-15
$wgExtraLanguageNames['aro'] = 'Araona'; # Araona / Siebrand 2010-08-25
$wgExtraLanguageNames['atj'] = 'Atikamekw'; # Atikamekw / Nikerabbit 2016-06-09
$wgExtraLanguageNames['awa'] = 'अवधी'; # Awadhi / Siebrand 2014-12-28
$wgExtraLanguageNames['ban'] = 'ᬩᬲᬩᬮᬶ'; # Balinese / Siebrand 2012-11-25
$wgExtraLanguageNames['bew'] = 'Bahasa Betawi'; # Betawi / Siebrand 2008-07-13
$wgExtraLanguageNames['bfq'] = 'படகா'; # UBadaga / Siebrand 2009-11-19
$wgExtraLanguageNames['ciw'] = 'Ojibwemowin'; # Chippewa / Siebrand 2014-03-21
$wgExtraLanguageNames['cja-latn'] = 'Cham Gah Pai'; # Western Cham (Latin script) / 2015-06-XX
$wgExtraLanguageNames['cjm-latn'] = 'Cham Gah Pur'; # Eastern Cham (Latin script) / Siebrand 2015-05-25
$wgExtraLanguageNames['cjy'] = '晉語'; # Jin Chinese (Jinnish) / 2015-06-XX
$wgExtraLanguageNames['cjy-hans'] = '晋语（简化字）'; # Jin Chinese (hans script) / 2015-06-XX
$wgExtraLanguageNames['cjy-hant'] = '晉語（正字）'; # Jin Chinese (hant script) / 2015-06-XX
$wgExtraLanguageNames['cnh'] = 'Lai holh'; # Haka Chin / Siebrand 2014-08-06
$wgExtraLanguageNames['din'] = 'Thuɔŋjäŋ'; # Dinka / Amir 2015-08-09
$wgExtraLanguageNames['dty'] = 'डोटेली'; # Dotyali / Siebrand 2014-11-16
$wgExtraLanguageNames['es-formal'] = 'español (formal)'; # Spanish (formal address) / Siebrand 2010-11-22
$wgExtraLanguageNames['esu'] = 'Yup\'ik'; # Central Alaskan Yupik / Siebrand 2011-02-14
$wgExtraLanguageNames['fax'] = 'Fala'; # Fala / Nikerabbit 2016-06-22
$wgExtraLanguageNames['gah'] = 'Alekano'; # Alekano / Siebrand 2010-10-08
$wgExtraLanguageNames['gbz'] = 'Dari-e Mazdeyasnā'; # Zoroastrian Dari / Siebrand 2011-01-20
$wgExtraLanguageNames['gcf'] = 'Guadeloupean Creole French'; # Guadeloupean Creole French / Siebrand 2009-09-21
$wgExtraLanguageNames['gor'] = 'Hulontalo'; # Gorontalo / Siebrand 2014-12-28
$wgExtraLanguageNames['guc'] = 'Wayúu'; # Wayuu / Siebrand 2009-12-12
$wgExtraLanguageNames['gur'] = 'Gurenɛ'; # Farefare / Siebrand 2011-01-27
$wgExtraLanguageNames['hif-deva'] = 'फ़ीजी हिन्दी'; # Fiji Hindi (Devangari script) / Siebrand 2010-08-26
$wgExtraLanguageNames['hne'] = 'छत्तीसगढ़ी'; # Amir 2011-12-01
$wgExtraLanguageNames['hsn'] = '湘语'; # Xiang Chinese / Siebrand 2011-04-06
$wgExtraLanguageNames['hu-formal'] = 'Magyar (magázó)'; # Siebrand 2009-01-01
$wgExtraLanguageNames['izh'] = 'ižoran keel'; # Ingrian / Robin 2012-11-17 / Language classified as not written in Ethnologue. Should be removed.
$wgExtraLanguageNames['jdt-cyrl'] = 'жугьури'; # Judeo-Tat / Siebrand 2014-06-17
$wgExtraLanguageNames['kac'] = 'Jinghpaw'; # Jingpho / Siebrand 2014-04-08
$wgExtraLanguageNames['kbp'] = 'Kabɩyɛ'; # Kabiye / Niklas 2016-04-06
$wgExtraLanguageNames['kbd-latn'] = 'Qabardjajəbza'; # Kabardian (Latin script) / Siebrand 2010-02-21
$wgExtraLanguageNames['kea'] = 'Kabuverdianu'; # Kabuverdianu / Siebrand 2009-01-07
$wgExtraLanguageNames['kgp'] = 'Kaingáng'; # Siebrand 2008-12-05
$wgExtraLanguageNames['kjh'] = 'хакас'; # Khakas / Amire80 2014-06-17
$wgExtraLanguageNames['knn'] = 'महाराष्ट्रीय कोंकणी'; # Maharashtrian Konkani / 2015-XX-XX
$wgExtraLanguageNames['krl'] = 'Karjala'; # Karelian / Siebrand 2008-04-12
$wgExtraLanguageNames['ksf'] = 'Bafia'; # Robin 2011-10-21
$wgExtraLanguageNames['lkt'] = 'Lakȟótiyapi'; # Lakota / 2014-04-08
$wgExtraLanguageNames['lld'] = 'Ladin'; # Ladin / Siebrand 2009-09-23
$wgExtraLanguageNames['mfe'] = 'Morisyen'; # Robin 2011-10-18
$wgExtraLanguageNames['mic'] = 'Mi\'kmaq'; # Micmac / Nikerabbit 2012-02-27
$wgExtraLanguageNames['miq'] = 'Mískitu'; # Miskito / Siebrand 2013-07-02
$wgExtraLanguageNames['mnc'] = 'ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ'; # Manchu / Siebrand 2010-08-11
$wgExtraLanguageNames['mni'] = 'মেইতেই লোন্'; # Meitei / Siebrand 2008-02-11
$wgExtraLanguageNames['mnw'] = 'ဘာသာ မန်'; # Mon / Amir 2012-05-31
$wgExtraLanguageNames['mui'] = 'Musi'; # Musi / Siebrand 2010-02-11
$wgExtraLanguageNames['mwv'] = 'Behase Mentawei'; # Mentawai / Siebrand 2008-05-07
$wgExtraLanguageNames['mww-latn'] = 'Hmoob Dawb'; # Hmong Daw / Siebrand 2013-12-02
$wgExtraLanguageNames['njo'] = 'Ao'; # Ao Naga
$wgExtraLanguageNames['nqo'] = 'ߒߞߏ'; # N'Ko / Siebrand 2011-01-11
$wgExtraLanguageNames['olo'] = 'Livvin-Karjalan'; # Livvi-Karelian / Mjbmr 2015-08-06
$wgExtraLanguageNames['pbb'] = 'Nasa Yuwe'; # Páez / Siebrand 2013-08-08
$wgExtraLanguageNames['pis'] = 'Pijin'; # Pijin / Siebrand 2011-08-25
$wgExtraLanguageNames['pko'] = 'Pökoot'; # Pökoot
$wgExtraLanguageNames['ppl'] = 'Nawat'; # Pipil / Siebrand 2011-08-30
$wgExtraLanguageNames['prs'] = 'دری'; # Dari
$wgExtraLanguageNames['pru'] = 'Prūsiskan'; # Prussian
$wgExtraLanguageNames['rap'] = 'arero rapa nui'; # Rapa Nui / Siebrand 2009-11-13
$wgExtraLanguageNames['rcf'] = 'Kreol Réyoné'; # Réunion Creole French / 2014-04-08
$wgExtraLanguageNames['rki'] = 'ရခိုင်'; # Rakhine / Siebrand 2010-10-14
$wgExtraLanguageNames['rmf'] = 'kaalengo tšimb'; # Romani language spoken in Finland / Nike 2014-03-05
$wgExtraLanguageNames['rtm'] = 'Faeag Rotuma'; # Rotuman
$wgExtraLanguageNames['ruq-grek'] = 'Megleno-Romanian (Greek script)'; # Megleno-Romanian (Greek script) / Siebrand 2009-09-23
$wgExtraLanguageNames['rut'] = 'мыхӀабишды'; # Rutul / Robin 2012-07-24
$wgExtraLanguageNames['ryu'] = 'ʔucināguci'; # Central Okinawan / Siebrand 2008-08-28
$wgExtraLanguageNames['saz'] = 'ꢱꣃꢬꢵꢯ꣄ꢡ꣄ꢬꢵ'; # Saurashtra / Siebrand 2011-03-17
$wgExtraLanguageNames['shn'] = 'လိၵ်ႈတႆး'; # Shan / Siebrand 2011-09-06
$wgExtraLanguageNames['shy-latn'] = 'Tacawit'; # Tacawit (Latin script) / Siebrand 2015-05-25
$wgExtraLanguageNames['slr'] = 'Salırça'; # Salar / Siebrand 2008-08-18
$wgExtraLanguageNames['sly'] = 'Bahasa Selayar'; # A Selayar / Siebrand 2012-01-09
$wgExtraLanguageNames['smj'] = 'julevsámegiella'; # Lule Saami / Nikerabbit 2016-06-22
$wgExtraLanguageNames['smn'] = 'anarâškielâ'; # Inari Saami / Siebrand 2014-10-06
$wgExtraLanguageNames['swb'] = 'Shikomoro'; # Comorian
$wgExtraLanguageNames['sxu'] = 'Säggssch'; # Upper Saxon
$wgExtraLanguageNames['test'] = 'Test (site admin only)'; # Test
$wgExtraLanguageNames['tkr'] = 'ЦӀаьхна миз'; # Tsakhur / Siebrand 2011-04-26
$wgExtraLanguageNames['trp'] = 'Kokborok (Tripuri)'; # Kokborok
$wgExtraLanguageNames['tsd'] = 'Τσακωνικά'; # Tsakonian / Siebrand 2009-08-20
$wgExtraLanguageNames['ttt'] = 'Tati'; # Tat / Siebrand 2008-04-04
$wgExtraLanguageNames['twd'] = 'Tweants'; # Twents
$wgExtraLanguageNames['wls'] = 'Faka\'uvea'; # Fakauvea
$wgExtraLanguageNames['ydd'] = 'Eastern Yiddish'; # Eastern Yiddish / Siebrand 2009-09-23
$wgExtraLanguageNames['yrk'] = 'Ненэцяʼ вада'; # Tundra Nenets / Lcawte 2011-02-07
$wgExtraLanguageNames['yrl'] = 'ñe\'engatú'; # Nheengatu / Siebrand 2008-04-06
$wgExtraLanguageNames['yua'] = 'Maaya T\'aan'; # Yucatán Maya / Siebrand 2011-04-09
$wgExtraLanguageNames['zgh'] = 'ⵜⴰⵎⴰⵣⵉⵖⵜ'; # Standard Moroccan Tamazight / Siebrand 2014-03-11

$wgExtraLanguageNames['nl-be'] = 'nl-be'; # Nikerabbit 2008-xx-xx - For FreeCol
$wgExtraLanguageNames['es-mx'] = 'español de México'; # Mexico; for iNaturalist
$wgExtraLanguageNames['qqq'] = 'Message documentation'; # No linguistic content. Used for documenting messages
$wgExtraLanguageNames['ike'] = 'ᐃᓄᒃᑎᑐᑦ/inuktitut'; # Dummy to have portal appear in Special:SupportedLanguages
