forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-mysql', '10.2.1'
mod 'elastic-elasticsearch', '6.4.0'
mod 'elastic-kibana', '6.3.1'
mod 'thias-sysctl', '1.0.6'
mod 'puppetlabs-java', '6.0.0'
mod 'puppet-letsencrypt', '5.0.0'
mod 'puppetlabs-mount_core', '1.0.4'
mod 'puppetlabs-inifile', '3.1.0'
mod 'puppetlabs-firewall', '2.2.0'
