forge "https://forgeapi.puppetlabs.com"

mod 'camptocamp-systemd', '2.10.0'
mod 'elastic-elasticsearch', '6.4.0'
mod 'elastic-kibana',
	:git => 'https://github.com/elastic/puppet-kibana.git',
	:commit => '154284f2a848ace5afbcf6ebc9163c443631d377'
mod 'puppet-letsencrypt', '6.0.0'
mod 'puppetlabs-firewall', '2.8.0'
mod 'puppetlabs-inifile', '4.4.0'
mod 'puppetlabs-java', '6.5.0'
mod 'puppetlabs-mount_core', '1.0.4'
mod 'puppetlabs-mysql', '10.9.0'
mod 'thias-sysctl', '1.0.6'
