<?php
/** Local translatewiki fallback settings.
 *
 * Adding a value here makes the languages in it appear by default
 * as "assistant languages" to people who translate to the language listed
 * as the key and who have the default value in the assistant language
 * preferecnce. This value is added to the existing fallback language value
 * as defined in core MediaWiki.
 *
 */

$wgTranslateLanguageFallbacks['aae'] = [ 'sq', 'aln', 'it', 'scn', 'roa-tara' ];
$wgTranslateLanguageFallbacks['acf'] = 'fr';
$wgTranslateLanguageFallbacks['ada'] = [ 'gaa', 'tw', 'fat', 'gpe' ];
$wgTranslateLanguageFallbacks['af'] = 'nl';
$wgTranslateLanguageFallbacks['ajg'] = [ 'fr', 'ee', 'fon', 'guw' ];
$wgTranslateLanguageFallbacks['ale'] = [ 'ale-cyrl', 'ru', 'esu', 'ik', 'ike-cans', 'ike-latn', 'kl' ];
$wgTranslateLanguageFallbacks['ale-cyrl'] = [ 'ale', 'ru', 'esu', 'ik', 'ike-cans', 'ike-latn', 'kl' ];
$wgTranslateLanguageFallbacks['alt'] = [ 'atv', 'kjh', 'tyv' ];
$wgTranslateLanguageFallbacks['ann'] = [ 'ig', 'efi', 'ibb' ];
$wgTranslateLanguageFallbacks['apc'] = 'ar';
$wgTranslateLanguageFallbacks['aro'] = 'es';
$wgTranslateLanguageFallbacks['as'] = 'bn';
$wgTranslateLanguageFallbacks['atv'] = [ 'alt', 'kjh', 'tyv', 'ru' ]; # Amir 2020-06-06
$wgTranslateLanguageFallbacks['ba'] = [ 'tt-cyrl', 'ru' ];
$wgTranslateLanguageFallbacks['ban'] = [ 'id', 'jv' ];
$wgTranslateLanguageFallbacks['bas'] = [ 'fr' ];
$wgTranslateLanguageFallbacks['bbc-latn'] = [ 'id', 'ms' ]; # Robin 2011-20-16
$wgTranslateLanguageFallbacks['bcc'] = [ 'bgn', 'ur', 'ps' ]; # Amir 2023-07-31
$wgTranslateLanguageFallbacks['bdr'] = [ 'id', 'tl' ];
$wgTranslateLanguageFallbacks['bfa'] = [ 'din', 'ar' ];
$wgTranslateLanguageFallbacks['bfq'] = [ 'kn', 'ta' ];
$wgTranslateLanguageFallbacks['bft'] = 'ur';
$wgTranslateLanguageFallbacks['bgc'] = 'hi';
$wgTranslateLanguageFallbacks['bgn'] = [ 'bcc', 'ur', 'ps' ]; # Amir 2023-07-31
$wgTranslateLanguageFallbacks['bkm'] = 'fr';
$wgTranslateLanguageFallbacks['bm'] = 'nqo';
$wgTranslateLanguageFallbacks['bnn'] = [ 'zh-hant' ];
$wgTranslateLanguageFallbacks['bo'] = [ 'dz', 'zh-hans' ];
$wgTranslateLanguageFallbacks['bol'] = [ 'kai', 'ha' ];
$wgTranslateLanguageFallbacks['bom'] = [ 'ha', 'ig', 'yo' ];
$wgTranslateLanguageFallbacks['bug-bugi'] = [ 'bug', 'mak', 'mak-bugi', 'id' ];
$wgTranslateLanguageFallbacks['bum'] = [ 'fr' ];
$wgTranslateLanguageFallbacks['bwr'] = [ 'ha', 'kr', 'ar' ];
$wgTranslateLanguageFallbacks['bxr'] = [ 'mn', 'xal' ];
$wgTranslateLanguageFallbacks['bzj'] = [ 'jam', 'es' ];
$wgTranslateLanguageFallbacks['bzs'] = [ 'pt-br', 'pt' ];
$wgTranslateLanguageFallbacks['cak'] = [ 'es' ];
$wgTranslateLanguageFallbacks['cja-latn'] = [ 'km' ];
$wgTranslateLanguageFallbacks['cjm-latn'] = [ 'vi' ];
$wgTranslateLanguageFallbacks['cjy-hans'] = [ 'zh-hans' ];
$wgTranslateLanguageFallbacks['cjy-hant'] = [ 'zh-hant' ];
$wgTranslateLanguageFallbacks['cnh'] = [ 'my' ];
$wgTranslateLanguageFallbacks['cps'] = [ 'tl' ];
$wgTranslateLanguageFallbacks['cpx-latn'] = [ 'cpx-hant', 'cpx-hans', 'cdo' ];
$wgTranslateLanguageFallbacks['crh-ro'] = [ 'crh-latn' ];
$wgTranslateLanguageFallbacks['cs'] = [ 'sk', 'de', 'fr', 'ru', 'pl' ];
$wgTranslateLanguageFallbacks['da'] = [ 'nn', 'nb', 'sv' ]; # Siebrand 2008-03-23
$wgTranslateLanguageFallbacks['dar'] = [ 'av', 'ce', 'ru', 'az' ];
$wgTranslateLanguageFallbacks['ddn'] = [ 'fr', 'fon', 'yo', 'ha' ];
$wgTranslateLanguageFallbacks['dga'] = [ 'dag', 'fr', 'mos', 'gur' ];
$wgTranslateLanguageFallbacks['dz'] = [ 'bo', 'hi', 'ne', 'zh-hans' ];
$wgTranslateLanguageFallbacks['ee'] = [ 'fr', 'ajg', 'fon', 'guw' ];
$wgTranslateLanguageFallbacks['efi'] = [ 'fr', 'ig', 'yo', 'ha' ];
$wgTranslateLanguageFallbacks['egl'] = [ 'it', 'rgn' ];
$wgTranslateLanguageFallbacks['es-mx'] = 'es';
$wgTranslateLanguageFallbacks['esu'] = [ 'ale', 'ale-cyrl', 'ik', 'ike-cans', 'ike-latn', 'kl' ];
$wgTranslateLanguageFallbacks['et'] = 'fi';
$wgTranslateLanguageFallbacks['fat'] = 'tw';
$wgTranslateLanguageFallbacks['fax'] = 'es';
$wgTranslateLanguageFallbacks['fi'] = [ 'de', 'sv', 'et', 'vro' ];
$wgTranslateLanguageFallbacks['fit'] = [ 'fi', 'sv' ]; # Robin 2011-09-27
$wgTranslateLanguageFallbacks['fon'] = [ 'ajg', 'ee', 'guw', 'yo' ];
$wgTranslateLanguageFallbacks['fy'] = 'nl';
$wgTranslateLanguageFallbacks['gaa'] = [ 'ada', 'tw', 'fat', 'bci' ];
$wgTranslateLanguageFallbacks['gbm'] = [ 'hi', 'ne', 'dty' ];
$wgTranslateLanguageFallbacks['gcf'] = [ 'fr', 'ht' ];
$wgTranslateLanguageFallbacks['guw'] = [ 'fr', 'fon', 'ajg', 'ee', 'yo' ];
$wgTranslateLanguageFallbacks['hak-hans'] = [ 'hak-hant', 'hak', 'hak-latn', 'zh-hans' ];
$wgTranslateLanguageFallbacks['hak-hant'] = [ 'hak-hans', 'hak', 'hak-latn', 'zh-hant' ];
$wgTranslateLanguageFallbacks['hak-latn'] = [ 'hak-hant', 'hak-hans', 'hak' ];
$wgTranslateLanguageFallbacks['hi'] = 'mr'; # Siebrand 2008-03-25
$wgTranslateLanguageFallbacks['hif-deva'] = 'hi'; # Siebrand 2008-02-12
$wgTranslateLanguageFallbacks['hno'] = [ 'pnb', 'skr-arab', 'ur', 'pa' ];
$wgTranslateLanguageFallbacks['hoc'] = [ 'or', 'sat', 'hi', 'te' ];
$wgTranslateLanguageFallbacks['hy'] = 'ru';
$wgTranslateLanguageFallbacks['ia'] = [ 'fr', 'it', 'es', 'pt' ];
$wgTranslateLanguageFallbacks['ibb'] = [ 'ig', 'efi', 'ann' ];
$wgTranslateLanguageFallbacks['igl'] = [ 'yo', 'ig', 'ha' ];
$wgTranslateLanguageFallbacks['ik'] = [ 'ale', 'ale-cyrl', 'esu', 'ike-cans', 'ike-latn', 'kl' ];
$wgTranslateLanguageFallbacks['ike-cans'] = [ 'ale', 'ale-cyrl', 'esu', 'ik', 'ike-latn', 'kl' ];
$wgTranslateLanguageFallbacks['ike-latn'] = [ 'ale', 'ale-cyrl', 'esu', 'ik', 'ike-cans', 'kl' ];
$wgTranslateLanguageFallbacks['ish'] = [ 'yo', 'ig', 'ha' ];
$wgTranslateLanguageFallbacks['jdt-cyrl'] = 'ru';
$wgTranslateLanguageFallbacks['jje'] = 'ko';
$wgTranslateLanguageFallbacks['jv'] = 'jv-java';
$wgTranslateLanguageFallbacks['jv-java'] = [ 'jv', 'id' ];
$wgTranslateLanguageFallbacks['kac'] = [ 'my' ];
$wgTranslateLanguageFallbacks['kai'] = [ 'bol', 'ha' ];
$wgTranslateLanguageFallbacks['kck'] = [ 'sn', 'tn', 've' ];
$wgTranslateLanguageFallbacks['kgp'] = [ 'pt', 'pt-br' ];
$wgTranslateLanguageFallbacks['ki'] = 'sw';
$wgTranslateLanguageFallbacks['kjh'] = [ 'alt', 'atv', 'tyv' ];
$wgTranslateLanguageFallbacks['kl'] = [ 'ale', 'ale-cyrl', 'esu', 'ik', 'ike-cans', 'ike-latn' ];
$wgTranslateLanguageFallbacks['knn'] = 'hi';
$wgTranslateLanguageFallbacks['kr'] = [ 'ha', 'ar', 'fr' ];
$wgTranslateLanguageFallbacks['ks-arab'] = 'ur'; # Robin
$wgTranslateLanguageFallbacks['ks-deva'] = 'hi'; # Robin
$wgTranslateLanguageFallbacks['ksf'] = [ 'fr' ]; # Robin 2011-10-21
$wgTranslateLanguageFallbacks['kus'] = [ 'dag', 'fr', 'mos', 'gur' ];
$wgTranslateLanguageFallbacks['lag'] = [ 'sw' ]; # Amir 2017-05-03
$wgTranslateLanguageFallbacks['lki'] = [ 'fa', 'lrc', 'sdh' ];
$wgTranslateLanguageFallbacks['lus'] = [ 'mrh', 'as', 'my' ];
$wgTranslateLanguageFallbacks['mag'] = [ 'bn', 'bho' ]; # Amir 2022-10-04
$wgTranslateLanguageFallbacks['mak'] = [ 'mak-bugi', 'bug', 'id' ]; # Amir 2022-08-20
$wgTranslateLanguageFallbacks['mak-bugi'] = [ 'mak', 'bug-bugi', 'bug', 'id' ]; # Amir 2022-08-20
$wgTranslateLanguageFallbacks['mey'] = [ 'ar', 'ary', 'fr', 'es' ]; # Amir 2023-01-27
$wgTranslateLanguageFallbacks['mfe'] = [ 'fr' ]; # Robin 2011-10-18
$wgTranslateLanguageFallbacks['miq'] = [ 'es' ];
$wgTranslateLanguageFallbacks['mnc'] = [ 'mnc-mong', 'zh-hans' ];
$wgTranslateLanguageFallbacks['mnc-mong'] = [ 'mnc', 'zh-hans' ];
$wgTranslateLanguageFallbacks['moe'] = [ 'fr' ];
$wgTranslateLanguageFallbacks['mos'] = [ 'fr', 'dag', 'gur', 'kbp', 'nmz' ];
$wgTranslateLanguageFallbacks['mrh'] = [ 'lus', 'as', 'my' ];
$wgTranslateLanguageFallbacks['mui'] = [ 'id' ];
$wgTranslateLanguageFallbacks['mvf'] = [ 'mn', 'zh-hans', 'ru' ];
$wgTranslateLanguageFallbacks['mwv'] = [ 'id' ];
$wgTranslateLanguageFallbacks['nb'] = [ 'nn', 'da', 'sv' ]; # Siebrand 2008-02-18
$wgTranslateLanguageFallbacks['nds-nl'] = [ 'nds', 'pdt' ];
$wgTranslateLanguageFallbacks['nds'] = [ 'da', 'nl', 'nds-nl', 'pdt' ];
$wgTranslateLanguageFallbacks['nit'] = [ 'wsg', 'te', 'hi' ];
$wgTranslateLanguageFallbacks['njo'] = [ 'as', 'hi' ];
$wgTranslateLanguageFallbacks['nmz'] = [ 'fr', 'kbp', 'ee' ]; # Only for translatewiki. Don't add these as fallback in core.
$wgTranslateLanguageFallbacks['nn'] = [ 'nb', 'sv', 'da' ]; # Siebrand 2008-02-18
$wgTranslateLanguageFallbacks['nod'] = [ 'th', 'nod-thai' ]; # Amir 2011-11-07
$wgTranslateLanguageFallbacks['nod-thai'] = [ 'th', 'nod' ]; # Siebrand 2017-05-20
$wgTranslateLanguageFallbacks['nog'] = 'ru';
$wgTranslateLanguageFallbacks['nqo'] = [ 'fr', 'bm' ];
$wgTranslateLanguageFallbacks['nso'] = [ 'st', 'tn', 'af' ];
$wgTranslateLanguageFallbacks['nus'] = [ 'ar', 'din' ];
$wgTranslateLanguageFallbacks['ny'] = [ 'tum', 'sw' ];
$wgTranslateLanguageFallbacks['nyn'] = [ 'lg', 'sw', 'rw', 'rn', 'rag' ];
$wgTranslateLanguageFallbacks['nzi'] = [ 'fr', 'tw', 'fat', 'bci' ];
$wgTranslateLanguageFallbacks['olo'] = [ 'ru' ]; # Mjbmr 2015-08-06
$wgTranslateLanguageFallbacks['ovd'] = [ 'se' ]; # Siebrand 2017-05-20
$wgTranslateLanguageFallbacks['pa'] = [ 'pnb' ];
$wgTranslateLanguageFallbacks['pap'] = [ 'pap-aw', 'nl', 'pt', 'es' ];
$wgTranslateLanguageFallbacks['pap-aw'] = [ 'pap', 'nl', 'pt', 'es' ];
$wgTranslateLanguageFallbacks['pbb'] = [ 'es' ];
$wgTranslateLanguageFallbacks['pnb'] = [ 'pa' ];
$wgTranslateLanguageFallbacks['ppl'] = [ 'es' ];
$wgTranslateLanguageFallbacks['prg'] = [ 'lv', 'lt', 'sgs', 'ltg', 'pl', 'ru' ];
$wgTranslateLanguageFallbacks['prs'] = [ 'fa', 'ps' ];
$wgTranslateLanguageFallbacks['pt-br'] = [ 'es', 'gl' ];
$wgTranslateLanguageFallbacks['pt'] = [ 'pt-br', 'es', 'gl' ]; # [[Thread:Support/wgTranslateLanguageFallbacks for Portuguese]]
$wgTranslateLanguageFallbacks['pwn'] = [ 'ami', 'tay', 'xsy', 'szy', 'trv' ];
$wgTranslateLanguageFallbacks['qwh'] = [ 'qu', 'es' ];
$wgTranslateLanguageFallbacks['rag'] = [ 'sw', 'nyn', 'rw', 'rn', 'lg' ];
$wgTranslateLanguageFallbacks['rcf'] = [ 'fr' ];
$wgTranslateLanguageFallbacks['rif'] = [ 'ar', 'fr' ]; # Robin 2011-09-30
$wgTranslateLanguageFallbacks['rki'] = [ 'my' ];
$wgTranslateLanguageFallbacks['rmc'] = [ 'sk', 'cs', 'hu' ];
$wgTranslateLanguageFallbacks['rmf'] = [ 'fi' ];
$wgTranslateLanguageFallbacks['rn'] = [ 'fr', 'rw', 'sw' ];
$wgTranslateLanguageFallbacks['rsk'] = [ 'uk', 'ru', 'rue' ];
$wgTranslateLanguageFallbacks['rut'] = [ 'az', 'ru', 'lez' ]; # Robin 2012-07-24
$wgTranslateLanguageFallbacks['rw'] = [ 'fr', 'rn', 'sw' ];
$wgTranslateLanguageFallbacks['ryu'] = [ 'ja' ];
$wgTranslateLanguageFallbacks['sat'] = [ 'or', 'hoc', 'hi', 'as' ];
$wgTranslateLanguageFallbacks['sc'] = [ 'sro', 'it' ];
$wgTranslateLanguageFallbacks['so'] = [ 'ar', 'it' ];
$wgTranslateLanguageFallbacks['saz'] = [ 'gu' ];
$wgTranslateLanguageFallbacks['se'] = [ 'fi', 'sv', 'nb', 'sma' ];
$wgTranslateLanguageFallbacks['shi'] = [ 'ar', 'fr' ]; # Robin 2011-09-27
$wgTranslateLanguageFallbacks['shy'] = [ 'fr', 'kab', 'arq', 'ar' ];
$wgTranslateLanguageFallbacks['sje'] = [ 'smj', 'se', 'sma', 'sv', 'nb', 'nn' ];
$wgTranslateLanguageFallbacks['sli'] = [ 'pl', 'szl' ];
$wgTranslateLanguageFallbacks['sly'] = [ 'id' ];
$wgTranslateLanguageFallbacks['sma'] = [ 'sv', 'nb', 'se' ];
$wgTranslateLanguageFallbacks['smj'] = [ 'nb' ];
$wgTranslateLanguageFallbacks['smn'] = [ 'se', 'sms', 'sma' ];
$wgTranslateLanguageFallbacks['sms'] = [ 'smn', 'fi', 'se' ];
$wgTranslateLanguageFallbacks['sro'] = [ 'sc' ];
$wgTranslateLanguageFallbacks['st'] = [ 'nso', 'tn', 'af' ];
$wgTranslateLanguageFallbacks['swb'] = 'sw';
$wgTranslateLanguageFallbacks['tdd'] = [ 'zh-hant', 'my', 'mnw', 'th', 'shn', 'nod' ];
$wgTranslateLanguageFallbacks['tji'] = 'zh-hans';
$wgTranslateLanguageFallbacks['tkr'] = 'ru';
$wgTranslateLanguageFallbacks['tly'] = [ 'tly-cyrl', 'az', 'azb', 'fa', 'ru' ];
$wgTranslateLanguageFallbacks['tly-cyrl'] = [ 'tly', 'az', 'azb', 'fa', 'ru' ];
$wgTranslateLanguageFallbacks['tn'] = [ 'nso', 'st', 'af' ];
$wgTranslateLanguageFallbacks['trp'] = [ 'bn', 'as', 'brx', 'hi' ];
$wgTranslateLanguageFallbacks['tru'] = 'arc'; # Robin 2012-02-18
$wgTranslateLanguageFallbacks['tsd'] = 'el';
$wgTranslateLanguageFallbacks['tsg'] = [ 'tl', 'ms' ];
$wgTranslateLanguageFallbacks['tum'] = [ 'ny', 'sw' ];
$wgTranslateLanguageFallbacks['tw'] = 'fat';
$wgTranslateLanguageFallbacks['tyv'] = [ 'alt', 'atv', 'kjh' ];
$wgTranslateLanguageFallbacks['ug-arab'] = [ 'ug-latn', 'zh-hans', 'zh-hant' ]; # Robin 2011-11-14
$wgTranslateLanguageFallbacks['ug-latn'] = [ 'ug-arab', 'ru' ]; # Robin 2011-11-14
$wgTranslateLanguageFallbacks['vmw'] = [ 'ts', 'sw', 'ss', 'ny', 'zu' ]; # Amir 2021-08-05
$wgTranslateLanguageFallbacks['wal'] = [ 'am' ];
$wgTranslateLanguageFallbacks['wsg'] = [ 'te', 'hi' ];
$wgTranslateLanguageFallbacks['xal'] = [ 'mn', 'bxr' ];
$wgTranslateLanguageFallbacks['xmm'] = [ 'id', 'ms' ];
$wgTranslateLanguageFallbacks['xsy'] = [ 'zh-hant' ]; # Amir 2017-05-03
$wgTranslateLanguageFallbacks['yoi'] = 'ja';
$wgTranslateLanguageFallbacks['yrk'] = 'ru'; # Lcawte 2011-02-07
$wgTranslateLanguageFallbacks['yrl'] = [ 'es', 'pt-br', 'gn' ];
$wgTranslateLanguageFallbacks['yua'] = 'es';
