<?php
/** Local translatewiki fallback settings.
 *
 * Adding a value here makes the languages in it appear by default
 * as "assistant languages" to people who translate to the language listed
 * as the key and who have the default value in the assistant language
 * preferecnce. This value is added to the existing fallback language value
 * as defined in core MediaWiki.
 *
 */

/** @phpcs-require-sorted-array */
$wgTranslateLanguageFallbacks = [
	'aae' => [ 'sq', 'aln', 'scn', 'roa-tara' ],
	'abr' => [ 'tw', 'fr' ],
	'acf' => [ 'fr', 'ht', 'gcf' ],
	'ada' => [ 'gaa', 'tw', 'fat', 'gpe' ],
	'af' => 'nl',
	'aii' => [ 'arc', 'tru', 'ar', 'sv', 'ru' ],
	'ajg' => [ 'fr', 'ee', 'fon', 'guw' ],
	'ale' => [ 'ale-cyrl', 'ru', 'esu', 'ik', 'ike-cans', 'ike-latn', 'kl' ],
	'ale-cyrl' => [ 'ale', 'ru', 'esu', 'ik', 'ike-cans', 'ike-latn', 'kl' ],
	'alt' => [ 'atv', 'kjh', 'tyv' ],
	'ann' => [ 'ig', 'efi', 'ibb' ],
	'apc' => 'fr',
	'aro' => 'es',
	'as' => 'bn',
	'atv' => [ 'alt', 'kjh', 'tyv', 'ru' ], # Amir 2020-06-06
	'ba' => [ 'tt-cyrl', 'ru' ],
	'ban' => [ 'ban-bali', 'jv' ],
	'ban-bali' => [ 'id', 'jv' ],
	'bas' => [ 'fr', 'dua' ],
	'bbc-latn' => 'ms', # Robin 2011-20-16
	'bcc' => [ 'bgn', 'ur', 'ps' ], # Amir 2023-07-31
	'bdr' => [ 'id', 'tl' ],
	'bfa' => [ 'din', 'ar' ],
	'bfq' => [ 'kn', 'ta' ],
	'bft' => 'ur',
	'bgc' => [ 'bgc-arab', 'hi', 'pa', 'pnb', 'ur' ],
	'bgc-arab' => [ 'bgc', 'pnb', 'skr-arab', 'ur', 'hi' ],
	'bgn' => [ 'bcc', 'ur', 'ps' ], # Amir 2023-07-31
	'bin' => [ 'ish', 'yo' ],
	'bkm' => 'fr',
	'bm' => 'nqo',
	'bnn' => 'zh-hant',
	'bo' => [ 'dz', 'zh-hans' ],
	'bol' => [ 'kai', 'ha' ],
	'bom' => [ 'ha', 'ig', 'yo' ],
	'bug-bugi' => [ 'bug', 'mak', 'mak-bugi', 'id' ],
	'bum' => 'fr',
	'bwr' => [ 'ha', 'kr', 'ar' ],
	'bxr' => [ 'mn', 'xal' ],
	'bzj' => [ 'jam', 'es' ],
	'bzs' => [ 'pt-br', 'pt' ],
	'cak' => 'es',
	'ccp' => 'bn',
	'cja-arab' => [ 'cja-cham', 'cja-latn', 'cjm-arab', 'cjm-cham', 'cjm-latn', 'km', 'ace', 'ms-arab', 'ms' ],
	'cja-cham' => [ 'cja-arab', 'cja-latn', 'cjm-arab', 'cjm-cham', 'cjm-latn', 'km', 'ace', 'ms-arab', 'ms' ],
	'cja-latn' => [ 'cja-arab', 'cja-cham', 'cjm-arab', 'cjm-cham', 'cjm-latn', 'km', 'ace', 'ms-arab', 'ms' ],
	'cjm-arab' => [ 'cja-arab', 'cja-cham', 'cja-latn', 'cjm-cham', 'cjm-latn', 'vi', 'ace', 'ms-arab', 'ms' ],
	'cjm-cham' => [ 'cja-arab', 'cja-cham', 'cja-latn', 'cjm-arab', 'cjm-latn', 'vi', 'ace', 'ms-arab', 'ms' ],
	'cjm-latn' => [ 'cja-arab', 'cja-cham', 'cja-latn', 'cjm-arab', 'cjm-cham', 'vi', 'ace', 'ms-arab', 'ms' ],
	'cjy-hans' => 'zh-hans',
	'cjy-hant' => 'zh-hant',
	'cnh' => 'my',
	'cps' => 'tl',
	'cpx-latn' => [ 'cpx-hant', 'cpx-hans', 'cdo' ],
	'crh-ro' => [ 'ro', 'crh-latn' ],
	'cs' => [ 'de', 'fr', 'ru', 'pl' ],
	'da' => [ 'nn', 'nb', 'sv' ], # Siebrand 2008-03-23
	'dar' => [ 'av', 'ce', 'ru', 'az' ],
	'ddn' => [ 'fr', 'fon', 'yo', 'ha' ],
	'dga' => [ 'dag', 'fr', 'mos', 'gur' ],
	'dru' => [ 'pwn', 'zh-hant' ],
	'dua' => [ 'fr', 'bas' ],
	'dz' => [ 'bo', 'hi', 'ne', 'zh-hans' ],
	'ee' => [ 'fr', 'ajg', 'fon', 'guw' ],
	'efi' => [ 'fr', 'ig', 'yo', 'ha' ],
	'egl' => 'rgn',
	'ekp' => [ 'ig', 'pcm' ],
	'es-mx' => 'es',
	'esu' => [ 'ale', 'ale-cyrl', 'ik', 'ike-cans', 'ike-latn', 'kl' ],
	'et' => 'fi',
	'fat' => 'tw',
	'fax' => 'es',
	'fi' => [ 'de', 'sv', 'et', 'vro' ],
	'fit' => [ 'sv' ], # Robin 2011-09-27
	'fon' => [ 'ajg', 'ee', 'guw', 'yo' ],
	'fy' => 'nl',
	'gaa' => [ 'ada', 'tw', 'fat', 'bci' ],
	'gbm' => [ 'hi', 'ne', 'dty' ],
	'gcf' => [ 'acf', 'gcr', 'ht' ],
	'guw' => [ 'fr', 'fon', 'ajg', 'ee', 'yo' ],
	'hak-hans' => [ 'hak-hant', 'hak', 'hak-latn', 'zh-hans' ],
	'hak-hant' => [ 'hak-hans', 'hak', 'hak-latn', 'zh-hant' ],
	'hak-latn' => [ 'hak-hant', 'hak-hans', 'hak' ],
	'hi' => 'mr', # Siebrand 2008-03-25
	'hif-deva' => 'hi', # Siebrand 2008-02-12
	'hke' => [ 'fr', 'sw', 'kg' ],
	'hno' => [ 'pnb', 'skr-arab', 'ur', 'pa' ],
	'hoc' => [ 'or', 'sat', 'hi', 'te' ],
	'hy' => 'ru',
	'ia' => [ 'fr', 'it', 'es', 'pt' ],
	'iba' => 'id',
	'ibb' => [ 'ig', 'efi', 'ann' ],
	'igb' => [ 'nup', 'yo', 'ig', 'ha' ],
	'igl' => [ 'yo', 'ig', 'ha' ],
	'ik' => [ 'ale', 'ale-cyrl', 'esu', 'ike-cans', 'ike-latn', 'kl' ],
	'ike-cans' => [ 'ale', 'ale-cyrl', 'esu', 'ik', 'ike-latn', 'kl' ],
	'ike-latn' => [ 'ale', 'ale-cyrl', 'esu', 'ik', 'ike-cans', 'kl' ],
	'ish' => [ 'bin', 'yo', 'ig', 'ha' ],
	'isv' => [ 'isv-latn', 'isv-cyrl' ],
	'isv-cyrl' => 'isv-latn',
	'isv-latn' => 'isv-cyrl',
	'jac' => 'es',
	'jdt-cyrl' => 'ru',
	'jje' => 'ko',
	'jv' => 'jv-java',
	'jv-java' => [ 'jv', 'id' ],
	'kac' => 'my',
	'kai' => [ 'bol', 'ha' ],
	'kaj' => [ 'kcg', 'ha', 'ff', 'yo' ],
	'kcg' => [ 'kaj', 'ha', 'ff', 'yo' ],
	'kck' => [ 'sn', 'tn', 've' ],
	'kge' => 'kge-arab',
	'kge-arab' => [ 'kge', 'id' ],
	'kgp' => [ 'pt', 'pt-br' ],
	'ki' => 'sw',
	'kip' => [ 'ne', 'new' ],
	'kjh' => [ 'alt', 'atv', 'tyv' ],
	'kl' => [ 'ale', 'ale-cyrl', 'esu', 'ik', 'ike-cans', 'ike-latn' ],
	'knn' => 'hi',
	'koi' => [ 'kv', 'udm' ],
	'kr' => [ 'ha', 'ar', 'fr' ],
	'ks-arab' => 'ur', # Robin
	'ks-deva' => 'hi', # Robin
	'ksf' => 'fr', # Robin 2011-10-21
	'kus' => [ 'dag', 'fr', 'mos', 'gur' ],
	'kv' => [ 'koi', 'udm' ],
	'lag' => 'sw', # Amir 2017-05-03
	'lki' => [ 'lrc', 'sdh' ],
	'lou' => [ 'fr', 'ht', 'acf', 'gcf' ],
	'lua' => [ 'fr', 'kg', 'sw', 'ln' ],
	'lue' => [ 'ny', 'tum', 'loz' ],
	'lus' => [ 'mrh', 'as', 'my' ],
	'mag' => [ 'bn', 'bho' ], # Amir 2022-10-04
	'mak' => [ 'mak-bugi', 'bug', 'id' ], # Amir 2022-08-20
	'mak-bugi' => [ 'mak', 'bug-bugi', 'bug', 'id' ], # Amir 2022-08-20
	'mey' => [ 'ar', 'ary', 'fr', 'es' ], # Amir 2023-01-27
	'mfe' => 'fr', # Robin 2011-10-18
	'miq' => 'es',
	'mnc' => [ 'mnc-mong', 'zh-hans' ],
	'mnc-mong' => [ 'mnc', 'zh-hans' ],
	'moe' => 'fr',
	'mos' => [ 'fr', 'dag', 'gur', 'kbp', 'nmz' ],
	'mrh' => [ 'lus', 'as', 'my' ],
	'msi' => [ 'ms', 'id' ],
	'mvf' => [ 'mn', 'zh-hans', 'ru' ],
	'mwv' => 'id',
	'nan' => [ 'nan-latn-pehoeji', 'nan-latn-tailo', 'nan-hant', 'nan-hans', 'zh-hans', 'zh-hant' ],
	'nan-hans' => [ 'nan-hant', 'nan-latn-pehoeji', 'nan-latn-tailo', 'nan', 'zh-hans', 'zh-hant' ],
	'nan-latn-pehoeji' => [ 'nan-hans' ],
	'nan-latn-tailo' => [ 'nan-hans' ],
	'naq' => [ 'af', 'de', 'kj', 'ng', 'tn', 'xh', 'zu' ],
	'nb' => [ 'nn', 'da', 'sv' ], # Siebrand 2008-02-18
	'nd' => [ 'sn', 'zu', 'ny', 'kck' ],
	'nds' => [ 'da', 'nl', 'nds-nl', 'pdt' ],
	'nds-nl' => [ 'nds', 'pdt' ],
	'nit' => [ 'wsg', 'te', 'hi' ],
	'njo' => [ 'as', 'hi' ],
	'nmz' => [ 'fr', 'kbp', 'ee' ], # Only for translatewiki. Don't add these as fallback in core.
	'nn' => [ 'sv', 'da' ], # Siebrand 2008-02-18
	'nnh' => [ 'fr', 'bas', 'dua' ],
	'nod' => [ 'th', 'nod-thai' ], # Amir 2011-11-07
	'nod-thai' => [ 'th', 'nod' ], # Siebrand 2017-05-20
	'nog' => 'ru',
	'nqo' => [ 'fr', 'bm' ],
	'nso' => [ 'st', 'tn', 'af' ],
	'nup' => [ 'ha', 'yo' ],
	'nus' => [ 'ar', 'din' ],
	'ny' => [ 'tum', 'sw' ],
	'nyn' => [ 'lg', 'sw', 'rw', 'rn', 'rag' ],
	'nzi' => [ 'fr', 'tw', 'fat', 'bci' ],
	'olo' => 'ru', # Mjbmr 2015-08-06
	'ovd' => 'sv', # Jon Harald 2024-01-12
	'pa' => 'pnb',
	'pap' => [ 'pap-aw', 'nl', 'pt', 'es' ],
	'pap-aw' => [ 'pap', 'nl', 'pt', 'es' ],
	'pbb' => 'es',
	'pey' => [ 'id', 'nl' ],
	'pnb' => 'pa',
	'pnt' => [ 'ru', 'tr', 'ka', 'lzz', 'uk', 'hy', 'hyw' ],
	'ppl' => 'es',
	'prg' => [ 'lv', 'lt', 'sgs', 'ltg', 'pl', 'ru' ],
	'prs' => [ 'fa', 'ps' ],
	'pt' => [ 'es', 'gl' ], # [[Thread:Support/wgTranslateLanguageFallbacks for Portuguese]]
	'pt-br' => [ 'es', 'gl' ],
	'pwn' => [ 'ami', 'tay', 'xsy', 'szy', 'trv' ],
	'qwh' => [ 'qu', 'es' ],
	'rag' => [ 'sw', 'nyn', 'rw', 'rn', 'lg' ],
	'rcf' => 'fr',
	'rif' => [ 'ar', 'fr' ], # Robin 2011-09-30
	'rki' => 'my',
	'rmc' => [ 'sk', 'cs', 'hu' ],
	'rmf' => 'fi',
	'rn' => [ 'fr', 'rw', 'sw' ],
	'rsk' => [ 'uk', 'ru', 'rue' ],
	'rut' => [ 'az', 'lez' ], # Robin 2012-07-24
	'rw' => [ 'fr', 'rn', 'sw' ],
	'ryu' => 'ja',
	'sat' => [ 'or', 'hoc', 'hi', 'as' ],
	'saz' => 'gu',
	'sc' => [ 'sro', 'it' ],
	'se' => [ 'fi', 'sv', 'nb', 'sma', 'smj', 'sju', 'smn' ], # Jon Harald 2024-01-12
	'shi' => [ 'ar', 'shi-latn' ], # Robin 2011-09-27
	'shy' => [ 'fr', 'kab', 'arq', 'ar' ],
	'sje' => [ 'smj', 'se', 'sma', 'sv', 'nb', 'nn' ],
	'sju' => [ 'sje', 'sma', 'smj', 'se', 'sv', 'nb', 'nn' ],
	'sli' => [ 'pl', 'szl' ],
	'sly' => 'id',
	'sma' => [ 'se', 'sje', 'sju' ], # Jon Harald 2024-01-12
	'smj' => [ 'nb', 'sje', 'sju' ], # Jon Harald 2024-01-12
	'smn' => [ 'se', 'sms', 'sje', 'sju', 'sma', 'smj' ], # Jon Harald 2024-01-12
	'sms' => [ 'smn', 'fi', 'se' ],
	'so' => [ 'ar', 'it' ],
	'sro' => 'sc',
	'st' => [ 'nso', 'tn', 'af' ],
	'swb' => 'sw',
	'tdd' => [ 'zh-hant', 'my', 'mnw', 'th', 'shn', 'nod' ],
	'tg-cyrl' => [ 'ru', 'fa' ],
	'ti' => [ 'tig', 'am', 'ar' ],
	'tig' => [ 'ti', 'am', 'ar' ],
	'tji' => 'zh-hans',
	'tkr' => 'ru',
	'tly' => [ 'tly-cyrl', 'az', 'azb', 'fa', 'ru' ],
	'tly-cyrl' => [ 'tly', 'az', 'azb', 'fa', 'ru' ],
	'tn' => [ 'nso', 'st', 'af' ],
	'toi' => [ 'ny', 'tum', 'sn', 'lue' ],
	'trp' => [ 'bn', 'as', 'brx', 'hi' ],
	'tru' => 'arc', # Robin 2012-02-18
	'trw' => [ 'ps', 'ur' ],
	'tsd' => 'el',
	'tsg' => [ 'tl', 'ms' ],
	'tum' => [ 'ny', 'sw' ],
	'tw' => 'fat',
	'tyv' => [ 'alt', 'atv', 'kjh' ],
	'udm' => [ 'koi', 'kv' ],
	'ug-arab' => [ 'ug-latn', 'zh-hans', 'zh-hant' ], # Robin 2011-11-14
	'ug-latn' => [ 'ug-arab', 'ru' ], # Robin 2011-11-14
	'vmw' => [ 'ts', 'sw', 'ss', 'ny', 'zu' ], # Amir 2021-08-05
	'wal' => 'am',
	'wlx' => [ 'dga', 'mos', 'gur', 'dag' ],
	'wsg' => [ 'te', 'hi' ],
	'xal' => [ 'mn', 'bxr' ],
	'xmm' => [ 'id', 'ms' ],
	'xsy' => 'zh-hant', # Amir 2017-05-03
	'yoi' => 'ja',
	'yrk' => 'ru', # Lcawte 2011-02-07
	'yrl' => [ 'es', 'pt-br', 'gn' ],
	'yua' => 'es',
	'zmi' => [ 'ms', 'min', 'id' ],
];
