; file managed by puppet

opcache.enable=1
opcache.enable_cli=1

; 2026-09-03 usage is ~492 MiB, so retain substantial headroom.
opcache.memory_consumption=1024

; 2026-09-03 usage is ~87 MiB.
opcache.interned_strings_buffer=128

; 2026-09-03 ~7,900 cached scripts / 32,531 available keys.
opcache.max_accelerated_files=24000

opcache.max_wasted_percentage=10
opcache.max_file_size=0

; Production deployments restart PHP-FPM, but automatic
; revalidation is useful for canary testing.
opcache.validate_timestamps=1
opcache.revalidate_freq=1
opcache.revalidate_path=1
